// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mtikv_clipb.proto

package mtikv_cli

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BeginTxnRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeginTxnRequest) Reset()         { *m = BeginTxnRequest{} }
func (m *BeginTxnRequest) String() string { return proto.CompactTextString(m) }
func (*BeginTxnRequest) ProtoMessage()    {}
func (*BeginTxnRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dedcbe7626113226, []int{0}
}

func (m *BeginTxnRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeginTxnRequest.Unmarshal(m, b)
}
func (m *BeginTxnRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeginTxnRequest.Marshal(b, m, deterministic)
}
func (m *BeginTxnRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeginTxnRequest.Merge(m, src)
}
func (m *BeginTxnRequest) XXX_Size() int {
	return xxx_messageInfo_BeginTxnRequest.Size(m)
}
func (m *BeginTxnRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BeginTxnRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BeginTxnRequest proto.InternalMessageInfo

type BeginTxnResponse struct {
	TransID              uint64   `protobuf:"varint,1,opt,name=transID,proto3" json:"transID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeginTxnResponse) Reset()         { *m = BeginTxnResponse{} }
func (m *BeginTxnResponse) String() string { return proto.CompactTextString(m) }
func (*BeginTxnResponse) ProtoMessage()    {}
func (*BeginTxnResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dedcbe7626113226, []int{1}
}

func (m *BeginTxnResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeginTxnResponse.Unmarshal(m, b)
}
func (m *BeginTxnResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeginTxnResponse.Marshal(b, m, deterministic)
}
func (m *BeginTxnResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeginTxnResponse.Merge(m, src)
}
func (m *BeginTxnResponse) XXX_Size() int {
	return xxx_messageInfo_BeginTxnResponse.Size(m)
}
func (m *BeginTxnResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BeginTxnResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BeginTxnResponse proto.InternalMessageInfo

func (m *BeginTxnResponse) GetTransID() uint64 {
	if m != nil {
		return m.TransID
	}
	return 0
}

type CommitTxnRequest struct {
	TransID              uint64   `protobuf:"varint,1,opt,name=transID,proto3" json:"transID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitTxnRequest) Reset()         { *m = CommitTxnRequest{} }
func (m *CommitTxnRequest) String() string { return proto.CompactTextString(m) }
func (*CommitTxnRequest) ProtoMessage()    {}
func (*CommitTxnRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dedcbe7626113226, []int{2}
}

func (m *CommitTxnRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitTxnRequest.Unmarshal(m, b)
}
func (m *CommitTxnRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitTxnRequest.Marshal(b, m, deterministic)
}
func (m *CommitTxnRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitTxnRequest.Merge(m, src)
}
func (m *CommitTxnRequest) XXX_Size() int {
	return xxx_messageInfo_CommitTxnRequest.Size(m)
}
func (m *CommitTxnRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitTxnRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommitTxnRequest proto.InternalMessageInfo

func (m *CommitTxnRequest) GetTransID() uint64 {
	if m != nil {
		return m.TransID
	}
	return 0
}

type CommitTxnResponse struct {
	TransID              uint64   `protobuf:"varint,1,opt,name=transID,proto3" json:"transID,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitTxnResponse) Reset()         { *m = CommitTxnResponse{} }
func (m *CommitTxnResponse) String() string { return proto.CompactTextString(m) }
func (*CommitTxnResponse) ProtoMessage()    {}
func (*CommitTxnResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dedcbe7626113226, []int{3}
}

func (m *CommitTxnResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitTxnResponse.Unmarshal(m, b)
}
func (m *CommitTxnResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitTxnResponse.Marshal(b, m, deterministic)
}
func (m *CommitTxnResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitTxnResponse.Merge(m, src)
}
func (m *CommitTxnResponse) XXX_Size() int {
	return xxx_messageInfo_CommitTxnResponse.Size(m)
}
func (m *CommitTxnResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitTxnResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommitTxnResponse proto.InternalMessageInfo

func (m *CommitTxnResponse) GetTransID() uint64 {
	if m != nil {
		return m.TransID
	}
	return 0
}

func (m *CommitTxnResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GetRequest struct {
	TransID              uint64   `protobuf:"varint,1,opt,name=transID,proto3" json:"transID,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dedcbe7626113226, []int{4}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetTransID() uint64 {
	if m != nil {
		return m.TransID
	}
	return 0
}

func (m *GetRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type GetResponse struct {
	TransID              uint64   `protobuf:"varint,1,opt,name=transID,proto3" json:"transID,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dedcbe7626113226, []int{5}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetTransID() uint64 {
	if m != nil {
		return m.TransID
	}
	return 0
}

func (m *GetResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type SetRequest struct {
	TransID              uint64   `protobuf:"varint,1,opt,name=transID,proto3" json:"transID,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetRequest) Reset()         { *m = SetRequest{} }
func (m *SetRequest) String() string { return proto.CompactTextString(m) }
func (*SetRequest) ProtoMessage()    {}
func (*SetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dedcbe7626113226, []int{6}
}

func (m *SetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRequest.Unmarshal(m, b)
}
func (m *SetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRequest.Marshal(b, m, deterministic)
}
func (m *SetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRequest.Merge(m, src)
}
func (m *SetRequest) XXX_Size() int {
	return xxx_messageInfo_SetRequest.Size(m)
}
func (m *SetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetRequest proto.InternalMessageInfo

func (m *SetRequest) GetTransID() uint64 {
	if m != nil {
		return m.TransID
	}
	return 0
}

func (m *SetRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *SetRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type SetResponse struct {
	TransID              uint64   `protobuf:"varint,1,opt,name=transID,proto3" json:"transID,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetResponse) Reset()         { *m = SetResponse{} }
func (m *SetResponse) String() string { return proto.CompactTextString(m) }
func (*SetResponse) ProtoMessage()    {}
func (*SetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dedcbe7626113226, []int{7}
}

func (m *SetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetResponse.Unmarshal(m, b)
}
func (m *SetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetResponse.Marshal(b, m, deterministic)
}
func (m *SetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetResponse.Merge(m, src)
}
func (m *SetResponse) XXX_Size() int {
	return xxx_messageInfo_SetResponse.Size(m)
}
func (m *SetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetResponse proto.InternalMessageInfo

func (m *SetResponse) GetTransID() uint64 {
	if m != nil {
		return m.TransID
	}
	return 0
}

func (m *SetResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type DeleteRequest struct {
	TransID              uint64   `protobuf:"varint,1,opt,name=transID,proto3" json:"transID,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dedcbe7626113226, []int{8}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetTransID() uint64 {
	if m != nil {
		return m.TransID
	}
	return 0
}

func (m *DeleteRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type DeleteResponse struct {
	TransID              uint64   `protobuf:"varint,1,opt,name=transID,proto3" json:"transID,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dedcbe7626113226, []int{9}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetTransID() uint64 {
	if m != nil {
		return m.TransID
	}
	return 0
}

func (m *DeleteResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*BeginTxnRequest)(nil), "mtikv_cli.BeginTxnRequest")
	proto.RegisterType((*BeginTxnResponse)(nil), "mtikv_cli.BeginTxnResponse")
	proto.RegisterType((*CommitTxnRequest)(nil), "mtikv_cli.CommitTxnRequest")
	proto.RegisterType((*CommitTxnResponse)(nil), "mtikv_cli.CommitTxnResponse")
	proto.RegisterType((*GetRequest)(nil), "mtikv_cli.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "mtikv_cli.GetResponse")
	proto.RegisterType((*SetRequest)(nil), "mtikv_cli.SetRequest")
	proto.RegisterType((*SetResponse)(nil), "mtikv_cli.SetResponse")
	proto.RegisterType((*DeleteRequest)(nil), "mtikv_cli.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "mtikv_cli.DeleteResponse")
}

func init() { proto.RegisterFile("mtikv_clipb.proto", fileDescriptor_dedcbe7626113226) }

var fileDescriptor_dedcbe7626113226 = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x4d, 0x4f, 0xbb, 0x40,
	0x10, 0xc6, 0xff, 0xb4, 0xff, 0x56, 0x99, 0xfa, 0x52, 0x36, 0x6a, 0x10, 0x3d, 0x34, 0x7b, 0xea,
	0xc1, 0x70, 0xd0, 0xc4, 0x68, 0xd4, 0x34, 0x69, 0x6b, 0xd0, 0x83, 0xc6, 0x40, 0xef, 0xa6, 0x35,
	0x93, 0x66, 0xc3, 0xab, 0x65, 0x4b, 0xf4, 0x53, 0xfa, 0x95, 0x0c, 0x20, 0xb0, 0x45, 0x22, 0xda,
	0x1b, 0x3b, 0xf3, 0xfc, 0x9e, 0xd9, 0xcc, 0x3e, 0x80, 0xe2, 0x72, 0x66, 0x47, 0xcf, 0x2f, 0x0e,
	0x0b, 0x66, 0x7a, 0xb0, 0xf0, 0xb9, 0x4f, 0xe4, 0xbc, 0x44, 0x15, 0xd8, 0x1d, 0xe2, 0x9c, 0x79,
	0x93, 0x37, 0xcf, 0xc4, 0xd7, 0x25, 0x86, 0x9c, 0x9e, 0x40, 0xb7, 0x28, 0x85, 0x81, 0xef, 0x85,
	0x48, 0x54, 0xd8, 0xe0, 0x8b, 0xa9, 0x17, 0xde, 0x8f, 0x55, 0xa9, 0x27, 0xf5, 0xff, 0x9b, 0xd9,
	0x31, 0x56, 0x8f, 0x7c, 0xd7, 0x65, 0xbc, 0x70, 0xf8, 0x41, 0x3d, 0x00, 0x45, 0x50, 0xd7, 0x99,
	0x93, 0x2e, 0x34, 0xdd, 0x70, 0xae, 0x36, 0x7a, 0x52, 0x5f, 0x36, 0xe3, 0x4f, 0x7a, 0x01, 0x60,
	0x20, 0xaf, 0x1d, 0x14, 0x93, 0x36, 0xbe, 0x27, 0xe4, 0x96, 0x19, 0x7f, 0xd2, 0x1b, 0xe8, 0x24,
	0x64, 0xed, 0xd0, 0x3d, 0x68, 0x45, 0x53, 0x67, 0x89, 0x5f, 0x70, 0x7a, 0xa0, 0x8f, 0x00, 0xd6,
	0x5a, 0x83, 0x0b, 0xbf, 0xa6, 0xe8, 0x77, 0x09, 0x1d, 0xeb, 0x57, 0xd7, 0xf9, 0xbe, 0x83, 0x2b,
	0xd8, 0x1e, 0xa3, 0x83, 0x1c, 0xd7, 0x59, 0xc3, 0x35, 0xec, 0x64, 0xf0, 0xdf, 0x47, 0x9f, 0x7e,
	0x34, 0xa0, 0xf3, 0x30, 0x61, 0x76, 0x34, 0x72, 0x18, 0x7a, 0x9c, 0xdc, 0xc2, 0x66, 0x96, 0x15,
	0xa2, 0xe9, 0x79, 0xac, 0xf4, 0x52, 0xa6, 0xb4, 0xa3, 0xca, 0x5e, 0x7a, 0x01, 0xfa, 0x8f, 0xdc,
	0x81, 0x9c, 0xc7, 0x82, 0x88, 0xda, 0x72, 0xb4, 0xb4, 0xe3, 0xea, 0x66, 0xee, 0x74, 0x0e, 0x4d,
	0x0b, 0x39, 0xd9, 0x17, 0x64, 0xc5, 0xb3, 0x69, 0x07, 0xe5, 0xb2, 0xc8, 0x19, 0x25, 0xce, 0xa8,
	0xe6, 0x8c, 0x15, 0x6e, 0x00, 0xed, 0x74, 0x9d, 0x44, 0x15, 0x34, 0x2b, 0xcf, 0xa3, 0x1d, 0x56,
	0x74, 0x32, 0x83, 0xa1, 0x0c, 0xad, 0xa4, 0xfb, 0x24, 0xcd, 0xda, 0xc9, 0xdf, 0x79, 0xf6, 0x19,
	0x00, 0x00, 0xff, 0xff, 0x4c, 0x84, 0x15, 0x1a, 0xb2, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MTikvClientClient is the client API for MTikvClient service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MTikvClientClient interface {
	BeginTxn(ctx context.Context, in *BeginTxnRequest, opts ...grpc.CallOption) (*BeginTxnResponse, error)
	CommitTxn(ctx context.Context, in *CommitTxnRequest, opts ...grpc.CallOption) (*CommitTxnResponse, error)
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type mTikvClientClient struct {
	cc *grpc.ClientConn
}

func NewMTikvClientClient(cc *grpc.ClientConn) MTikvClientClient {
	return &mTikvClientClient{cc}
}

func (c *mTikvClientClient) BeginTxn(ctx context.Context, in *BeginTxnRequest, opts ...grpc.CallOption) (*BeginTxnResponse, error) {
	out := new(BeginTxnResponse)
	err := c.cc.Invoke(ctx, "/mtikv_cli.MTikvClient/BeginTxn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mTikvClientClient) CommitTxn(ctx context.Context, in *CommitTxnRequest, opts ...grpc.CallOption) (*CommitTxnResponse, error) {
	out := new(CommitTxnResponse)
	err := c.cc.Invoke(ctx, "/mtikv_cli.MTikvClient/CommitTxn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mTikvClientClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, "/mtikv_cli.MTikvClient/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mTikvClientClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/mtikv_cli.MTikvClient/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mTikvClientClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/mtikv_cli.MTikvClient/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MTikvClientServer is the server API for MTikvClient service.
type MTikvClientServer interface {
	BeginTxn(context.Context, *BeginTxnRequest) (*BeginTxnResponse, error)
	CommitTxn(context.Context, *CommitTxnRequest) (*CommitTxnResponse, error)
	Set(context.Context, *SetRequest) (*SetResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
}

// UnimplementedMTikvClientServer can be embedded to have forward compatible implementations.
type UnimplementedMTikvClientServer struct {
}

func (*UnimplementedMTikvClientServer) BeginTxn(ctx context.Context, req *BeginTxnRequest) (*BeginTxnResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BeginTxn not implemented")
}
func (*UnimplementedMTikvClientServer) CommitTxn(ctx context.Context, req *CommitTxnRequest) (*CommitTxnResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitTxn not implemented")
}
func (*UnimplementedMTikvClientServer) Set(ctx context.Context, req *SetRequest) (*SetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (*UnimplementedMTikvClientServer) Get(ctx context.Context, req *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedMTikvClientServer) Delete(ctx context.Context, req *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterMTikvClientServer(s *grpc.Server, srv MTikvClientServer) {
	s.RegisterService(&_MTikvClient_serviceDesc, srv)
}

func _MTikvClient_BeginTxn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginTxnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MTikvClientServer).BeginTxn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtikv_cli.MTikvClient/BeginTxn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MTikvClientServer).BeginTxn(ctx, req.(*BeginTxnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MTikvClient_CommitTxn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitTxnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MTikvClientServer).CommitTxn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtikv_cli.MTikvClient/CommitTxn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MTikvClientServer).CommitTxn(ctx, req.(*CommitTxnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MTikvClient_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MTikvClientServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtikv_cli.MTikvClient/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MTikvClientServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MTikvClient_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MTikvClientServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtikv_cli.MTikvClient/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MTikvClientServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MTikvClient_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MTikvClientServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtikv_cli.MTikvClient/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MTikvClientServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MTikvClient_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mtikv_cli.MTikvClient",
	HandlerType: (*MTikvClientServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BeginTxn",
			Handler:    _MTikvClient_BeginTxn_Handler,
		},
		{
			MethodName: "CommitTxn",
			Handler:    _MTikvClient_CommitTxn_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _MTikvClient_Set_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _MTikvClient_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _MTikvClient_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mtikv_clipb.proto",
}
