// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mtikv_clipb.proto

package mtikv_cli

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Error int32

const (
	Error_SUCCESS Error = 0
	Error_FAILED  Error = 1
	Error_INVALID Error = 2
)

var Error_name = map[int32]string{
	0: "SUCCESS",
	1: "FAILED",
	2: "INVALID",
}

var Error_value = map[string]int32{
	"SUCCESS": 0,
	"FAILED":  1,
	"INVALID": 2,
}

func (x Error) String() string {
	return proto.EnumName(Error_name, int32(x))
}

func (Error) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dedcbe7626113226, []int{0}
}

type BeginTxnRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeginTxnRequest) Reset()         { *m = BeginTxnRequest{} }
func (m *BeginTxnRequest) String() string { return proto.CompactTextString(m) }
func (*BeginTxnRequest) ProtoMessage()    {}
func (*BeginTxnRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dedcbe7626113226, []int{0}
}

func (m *BeginTxnRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeginTxnRequest.Unmarshal(m, b)
}
func (m *BeginTxnRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeginTxnRequest.Marshal(b, m, deterministic)
}
func (m *BeginTxnRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeginTxnRequest.Merge(m, src)
}
func (m *BeginTxnRequest) XXX_Size() int {
	return xxx_messageInfo_BeginTxnRequest.Size(m)
}
func (m *BeginTxnRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BeginTxnRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BeginTxnRequest proto.InternalMessageInfo

type BeginTxnResponse struct {
	TransID              uint64   `protobuf:"varint,1,opt,name=transID,proto3" json:"transID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BeginTxnResponse) Reset()         { *m = BeginTxnResponse{} }
func (m *BeginTxnResponse) String() string { return proto.CompactTextString(m) }
func (*BeginTxnResponse) ProtoMessage()    {}
func (*BeginTxnResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dedcbe7626113226, []int{1}
}

func (m *BeginTxnResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BeginTxnResponse.Unmarshal(m, b)
}
func (m *BeginTxnResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BeginTxnResponse.Marshal(b, m, deterministic)
}
func (m *BeginTxnResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BeginTxnResponse.Merge(m, src)
}
func (m *BeginTxnResponse) XXX_Size() int {
	return xxx_messageInfo_BeginTxnResponse.Size(m)
}
func (m *BeginTxnResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BeginTxnResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BeginTxnResponse proto.InternalMessageInfo

func (m *BeginTxnResponse) GetTransID() uint64 {
	if m != nil {
		return m.TransID
	}
	return 0
}

type CommitTxnRequest struct {
	TransID              uint64   `protobuf:"varint,1,opt,name=transID,proto3" json:"transID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitTxnRequest) Reset()         { *m = CommitTxnRequest{} }
func (m *CommitTxnRequest) String() string { return proto.CompactTextString(m) }
func (*CommitTxnRequest) ProtoMessage()    {}
func (*CommitTxnRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dedcbe7626113226, []int{2}
}

func (m *CommitTxnRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitTxnRequest.Unmarshal(m, b)
}
func (m *CommitTxnRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitTxnRequest.Marshal(b, m, deterministic)
}
func (m *CommitTxnRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitTxnRequest.Merge(m, src)
}
func (m *CommitTxnRequest) XXX_Size() int {
	return xxx_messageInfo_CommitTxnRequest.Size(m)
}
func (m *CommitTxnRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitTxnRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommitTxnRequest proto.InternalMessageInfo

func (m *CommitTxnRequest) GetTransID() uint64 {
	if m != nil {
		return m.TransID
	}
	return 0
}

type CommitTxnResponse struct {
	TransID              uint64   `protobuf:"varint,1,opt,name=transID,proto3" json:"transID,omitempty"`
	Error                Error    `protobuf:"varint,2,opt,name=error,proto3,enum=mtikv_cli.Error" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitTxnResponse) Reset()         { *m = CommitTxnResponse{} }
func (m *CommitTxnResponse) String() string { return proto.CompactTextString(m) }
func (*CommitTxnResponse) ProtoMessage()    {}
func (*CommitTxnResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dedcbe7626113226, []int{3}
}

func (m *CommitTxnResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitTxnResponse.Unmarshal(m, b)
}
func (m *CommitTxnResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitTxnResponse.Marshal(b, m, deterministic)
}
func (m *CommitTxnResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitTxnResponse.Merge(m, src)
}
func (m *CommitTxnResponse) XXX_Size() int {
	return xxx_messageInfo_CommitTxnResponse.Size(m)
}
func (m *CommitTxnResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitTxnResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommitTxnResponse proto.InternalMessageInfo

func (m *CommitTxnResponse) GetTransID() uint64 {
	if m != nil {
		return m.TransID
	}
	return 0
}

func (m *CommitTxnResponse) GetError() Error {
	if m != nil {
		return m.Error
	}
	return Error_SUCCESS
}

type RollBackTxnRequest struct {
	TransID              uint64   `protobuf:"varint,1,opt,name=transID,proto3" json:"transID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RollBackTxnRequest) Reset()         { *m = RollBackTxnRequest{} }
func (m *RollBackTxnRequest) String() string { return proto.CompactTextString(m) }
func (*RollBackTxnRequest) ProtoMessage()    {}
func (*RollBackTxnRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dedcbe7626113226, []int{4}
}

func (m *RollBackTxnRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RollBackTxnRequest.Unmarshal(m, b)
}
func (m *RollBackTxnRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RollBackTxnRequest.Marshal(b, m, deterministic)
}
func (m *RollBackTxnRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollBackTxnRequest.Merge(m, src)
}
func (m *RollBackTxnRequest) XXX_Size() int {
	return xxx_messageInfo_RollBackTxnRequest.Size(m)
}
func (m *RollBackTxnRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RollBackTxnRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RollBackTxnRequest proto.InternalMessageInfo

func (m *RollBackTxnRequest) GetTransID() uint64 {
	if m != nil {
		return m.TransID
	}
	return 0
}

type RollBackTxnResponse struct {
	TransID              uint64   `protobuf:"varint,1,opt,name=transID,proto3" json:"transID,omitempty"`
	Error                Error    `protobuf:"varint,2,opt,name=error,proto3,enum=mtikv_cli.Error" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RollBackTxnResponse) Reset()         { *m = RollBackTxnResponse{} }
func (m *RollBackTxnResponse) String() string { return proto.CompactTextString(m) }
func (*RollBackTxnResponse) ProtoMessage()    {}
func (*RollBackTxnResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dedcbe7626113226, []int{5}
}

func (m *RollBackTxnResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RollBackTxnResponse.Unmarshal(m, b)
}
func (m *RollBackTxnResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RollBackTxnResponse.Marshal(b, m, deterministic)
}
func (m *RollBackTxnResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RollBackTxnResponse.Merge(m, src)
}
func (m *RollBackTxnResponse) XXX_Size() int {
	return xxx_messageInfo_RollBackTxnResponse.Size(m)
}
func (m *RollBackTxnResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RollBackTxnResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RollBackTxnResponse proto.InternalMessageInfo

func (m *RollBackTxnResponse) GetTransID() uint64 {
	if m != nil {
		return m.TransID
	}
	return 0
}

func (m *RollBackTxnResponse) GetError() Error {
	if m != nil {
		return m.Error
	}
	return Error_SUCCESS
}

type GetRequest struct {
	TransID              uint64   `protobuf:"varint,1,opt,name=transID,proto3" json:"transID,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dedcbe7626113226, []int{6}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetTransID() uint64 {
	if m != nil {
		return m.TransID
	}
	return 0
}

func (m *GetRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type GetResponse struct {
	TransID              uint64   `protobuf:"varint,1,opt,name=transID,proto3" json:"transID,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Error                Error    `protobuf:"varint,3,opt,name=error,proto3,enum=mtikv_cli.Error" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dedcbe7626113226, []int{7}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetTransID() uint64 {
	if m != nil {
		return m.TransID
	}
	return 0
}

func (m *GetResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *GetResponse) GetError() Error {
	if m != nil {
		return m.Error
	}
	return Error_SUCCESS
}

type SetRequest struct {
	TransID              uint64   `protobuf:"varint,1,opt,name=transID,proto3" json:"transID,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetRequest) Reset()         { *m = SetRequest{} }
func (m *SetRequest) String() string { return proto.CompactTextString(m) }
func (*SetRequest) ProtoMessage()    {}
func (*SetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dedcbe7626113226, []int{8}
}

func (m *SetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRequest.Unmarshal(m, b)
}
func (m *SetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRequest.Marshal(b, m, deterministic)
}
func (m *SetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRequest.Merge(m, src)
}
func (m *SetRequest) XXX_Size() int {
	return xxx_messageInfo_SetRequest.Size(m)
}
func (m *SetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetRequest proto.InternalMessageInfo

func (m *SetRequest) GetTransID() uint64 {
	if m != nil {
		return m.TransID
	}
	return 0
}

func (m *SetRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *SetRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type SetResponse struct {
	TransID              uint64   `protobuf:"varint,1,opt,name=transID,proto3" json:"transID,omitempty"`
	Error                Error    `protobuf:"varint,2,opt,name=error,proto3,enum=mtikv_cli.Error" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetResponse) Reset()         { *m = SetResponse{} }
func (m *SetResponse) String() string { return proto.CompactTextString(m) }
func (*SetResponse) ProtoMessage()    {}
func (*SetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dedcbe7626113226, []int{9}
}

func (m *SetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetResponse.Unmarshal(m, b)
}
func (m *SetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetResponse.Marshal(b, m, deterministic)
}
func (m *SetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetResponse.Merge(m, src)
}
func (m *SetResponse) XXX_Size() int {
	return xxx_messageInfo_SetResponse.Size(m)
}
func (m *SetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetResponse proto.InternalMessageInfo

func (m *SetResponse) GetTransID() uint64 {
	if m != nil {
		return m.TransID
	}
	return 0
}

func (m *SetResponse) GetError() Error {
	if m != nil {
		return m.Error
	}
	return Error_SUCCESS
}

type DeleteRequest struct {
	TransID              uint64   `protobuf:"varint,1,opt,name=transID,proto3" json:"transID,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dedcbe7626113226, []int{10}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetTransID() uint64 {
	if m != nil {
		return m.TransID
	}
	return 0
}

func (m *DeleteRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type DeleteResponse struct {
	TransID              uint64   `protobuf:"varint,1,opt,name=transID,proto3" json:"transID,omitempty"`
	Error                Error    `protobuf:"varint,2,opt,name=error,proto3,enum=mtikv_cli.Error" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dedcbe7626113226, []int{11}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetTransID() uint64 {
	if m != nil {
		return m.TransID
	}
	return 0
}

func (m *DeleteResponse) GetError() Error {
	if m != nil {
		return m.Error
	}
	return Error_SUCCESS
}

func init() {
	proto.RegisterEnum("mtikv_cli.Error", Error_name, Error_value)
	proto.RegisterType((*BeginTxnRequest)(nil), "mtikv_cli.BeginTxnRequest")
	proto.RegisterType((*BeginTxnResponse)(nil), "mtikv_cli.BeginTxnResponse")
	proto.RegisterType((*CommitTxnRequest)(nil), "mtikv_cli.CommitTxnRequest")
	proto.RegisterType((*CommitTxnResponse)(nil), "mtikv_cli.CommitTxnResponse")
	proto.RegisterType((*RollBackTxnRequest)(nil), "mtikv_cli.RollBackTxnRequest")
	proto.RegisterType((*RollBackTxnResponse)(nil), "mtikv_cli.RollBackTxnResponse")
	proto.RegisterType((*GetRequest)(nil), "mtikv_cli.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "mtikv_cli.GetResponse")
	proto.RegisterType((*SetRequest)(nil), "mtikv_cli.SetRequest")
	proto.RegisterType((*SetResponse)(nil), "mtikv_cli.SetResponse")
	proto.RegisterType((*DeleteRequest)(nil), "mtikv_cli.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "mtikv_cli.DeleteResponse")
}

func init() { proto.RegisterFile("mtikv_clipb.proto", fileDescriptor_dedcbe7626113226) }

var fileDescriptor_dedcbe7626113226 = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x5b, 0x8f, 0x9a, 0x40,
	0x14, 0x16, 0x29, 0x5e, 0x0e, 0xad, 0xc5, 0xe9, 0x25, 0x94, 0x5e, 0x62, 0x78, 0x68, 0x4c, 0xd3,
	0xf2, 0x60, 0x93, 0xa6, 0x49, 0x1f, 0x1a, 0x05, 0x4a, 0x49, 0xac, 0x6d, 0x40, 0xdb, 0xc7, 0x46,
	0xcd, 0x64, 0x43, 0x40, 0x70, 0x61, 0x34, 0xbb, 0xff, 0x65, 0x7f, 0xec, 0x06, 0x58, 0x60, 0x64,
	0x59, 0x35, 0xc6, 0x37, 0xe6, 0x7c, 0x97, 0xf3, 0x31, 0x9c, 0x03, 0x74, 0x57, 0xc4, 0x71, 0xb7,
	0xff, 0x97, 0x9e, 0xb3, 0x5e, 0x28, 0xeb, 0x30, 0x20, 0x01, 0x6a, 0xe7, 0x25, 0xb9, 0x0b, 0x4f,
	0x47, 0xf8, 0xc2, 0xf1, 0xa7, 0x57, 0xbe, 0x85, 0x2f, 0x37, 0x38, 0x22, 0xf2, 0x47, 0x10, 0x8a,
	0x52, 0xb4, 0x0e, 0xfc, 0x08, 0x23, 0x11, 0x9a, 0x24, 0x9c, 0xfb, 0x91, 0xa9, 0x89, 0x4c, 0x8f,
	0xe9, 0x3f, 0xb2, 0xb2, 0x63, 0xcc, 0x56, 0x83, 0xd5, 0xca, 0x21, 0x85, 0xc3, 0x1e, 0xf6, 0x0c,
	0xba, 0x14, 0xfb, 0x90, 0x39, 0x7a, 0x0f, 0x1c, 0x0e, 0xc3, 0x20, 0x14, 0xeb, 0x3d, 0xa6, 0xdf,
	0x19, 0x08, 0x4a, 0x1e, 0x5c, 0xd1, 0xe3, 0xba, 0x95, 0xc2, 0xb2, 0x02, 0xc8, 0x0a, 0x3c, 0x6f,
	0x34, 0x5f, 0xba, 0x47, 0xc5, 0xf8, 0x07, 0xcf, 0x76, 0xf8, 0x67, 0x0b, 0xf2, 0x15, 0xc0, 0xc0,
	0xe4, 0x60, 0x00, 0x24, 0x00, 0xeb, 0xe2, 0xeb, 0xc4, 0xed, 0xb1, 0x15, 0x3f, 0xca, 0x18, 0xf8,
	0x44, 0x79, 0x30, 0xca, 0x73, 0xe0, 0xb6, 0x73, 0x6f, 0x83, 0xef, 0xc4, 0xe9, 0xa1, 0x08, 0xc8,
	0xee, 0x0f, 0x38, 0x01, 0xb0, 0x4f, 0x0a, 0x58, 0xf4, 0x65, 0xa9, 0xbe, 0xf2, 0x6f, 0xe0, 0xed,
	0xa3, 0x62, 0x1f, 0x7b, 0x83, 0xdf, 0xe0, 0x89, 0x86, 0x3d, 0x4c, 0xf0, 0x29, 0x97, 0x68, 0x41,
	0x27, 0x13, 0x9f, 0x2b, 0xd0, 0x87, 0x4f, 0xc0, 0x25, 0x67, 0xc4, 0x43, 0xd3, 0x9e, 0xa9, 0xaa,
	0x6e, 0xdb, 0x42, 0x0d, 0x01, 0x34, 0x7e, 0x0c, 0xcd, 0xb1, 0xae, 0x09, 0x4c, 0x0c, 0x98, 0x93,
	0xbf, 0xc3, 0xb1, 0xa9, 0x09, 0xf5, 0xc1, 0x0d, 0x0b, 0xad, 0x5f, 0x53, 0xc7, 0xdd, 0xaa, 0x9e,
	0x83, 0x74, 0x68, 0x65, 0xab, 0x84, 0x24, 0xaa, 0x41, 0x69, 0xe5, 0xa4, 0xd7, 0x95, 0x58, 0xfa,
	0x0a, 0x72, 0x0d, 0xfd, 0x84, 0x76, 0xbe, 0x35, 0x88, 0xe6, 0x96, 0x37, 0x4f, 0x7a, 0x53, 0x0d,
	0xe6, 0x4e, 0x13, 0xe0, 0xa9, 0xc1, 0x47, 0x6f, 0x29, 0xfa, 0xfd, 0x05, 0x92, 0xde, 0x3d, 0x04,
	0xe7, 0x7e, 0x5f, 0x80, 0xb5, 0x31, 0x41, 0x2f, 0x28, 0x62, 0x31, 0x5e, 0xd2, 0xcb, 0x72, 0x99,
	0xd6, 0x19, 0x25, 0x9d, 0x51, 0xad, 0x33, 0x76, 0x74, 0xdf, 0xa1, 0x91, 0x7e, 0x60, 0x24, 0x52,
	0x9c, 0x9d, 0x81, 0x91, 0x5e, 0x55, 0x20, 0x99, 0xc1, 0xa8, 0x0d, 0x5c, 0x82, 0xfe, 0x61, 0x16,
	0x8d, 0xe4, 0x67, 0xf8, 0xf9, 0x36, 0x00, 0x00, 0xff, 0xff, 0x59, 0x0a, 0xf5, 0x6b, 0x21, 0x05,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MTikvCliClient is the client API for MTikvCli service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MTikvCliClient interface {
	BeginTxn(ctx context.Context, in *BeginTxnRequest, opts ...grpc.CallOption) (*BeginTxnResponse, error)
	CommitTxn(ctx context.Context, in *CommitTxnRequest, opts ...grpc.CallOption) (*CommitTxnResponse, error)
	RollBackTxn(ctx context.Context, in *RollBackTxnRequest, opts ...grpc.CallOption) (*RollBackTxnResponse, error)
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type mTikvCliClient struct {
	cc *grpc.ClientConn
}

func NewMTikvCliClient(cc *grpc.ClientConn) MTikvCliClient {
	return &mTikvCliClient{cc}
}

func (c *mTikvCliClient) BeginTxn(ctx context.Context, in *BeginTxnRequest, opts ...grpc.CallOption) (*BeginTxnResponse, error) {
	out := new(BeginTxnResponse)
	err := c.cc.Invoke(ctx, "/mtikv_cli.MTikvCli/BeginTxn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mTikvCliClient) CommitTxn(ctx context.Context, in *CommitTxnRequest, opts ...grpc.CallOption) (*CommitTxnResponse, error) {
	out := new(CommitTxnResponse)
	err := c.cc.Invoke(ctx, "/mtikv_cli.MTikvCli/CommitTxn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mTikvCliClient) RollBackTxn(ctx context.Context, in *RollBackTxnRequest, opts ...grpc.CallOption) (*RollBackTxnResponse, error) {
	out := new(RollBackTxnResponse)
	err := c.cc.Invoke(ctx, "/mtikv_cli.MTikvCli/RollBackTxn", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mTikvCliClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, "/mtikv_cli.MTikvCli/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mTikvCliClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/mtikv_cli.MTikvCli/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mTikvCliClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/mtikv_cli.MTikvCli/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MTikvCliServer is the server API for MTikvCli service.
type MTikvCliServer interface {
	BeginTxn(context.Context, *BeginTxnRequest) (*BeginTxnResponse, error)
	CommitTxn(context.Context, *CommitTxnRequest) (*CommitTxnResponse, error)
	RollBackTxn(context.Context, *RollBackTxnRequest) (*RollBackTxnResponse, error)
	Set(context.Context, *SetRequest) (*SetResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
}

// UnimplementedMTikvCliServer can be embedded to have forward compatible implementations.
type UnimplementedMTikvCliServer struct {
}

func (*UnimplementedMTikvCliServer) BeginTxn(ctx context.Context, req *BeginTxnRequest) (*BeginTxnResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BeginTxn not implemented")
}
func (*UnimplementedMTikvCliServer) CommitTxn(ctx context.Context, req *CommitTxnRequest) (*CommitTxnResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitTxn not implemented")
}
func (*UnimplementedMTikvCliServer) RollBackTxn(ctx context.Context, req *RollBackTxnRequest) (*RollBackTxnResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RollBackTxn not implemented")
}
func (*UnimplementedMTikvCliServer) Set(ctx context.Context, req *SetRequest) (*SetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (*UnimplementedMTikvCliServer) Get(ctx context.Context, req *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedMTikvCliServer) Delete(ctx context.Context, req *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterMTikvCliServer(s *grpc.Server, srv MTikvCliServer) {
	s.RegisterService(&_MTikvCli_serviceDesc, srv)
}

func _MTikvCli_BeginTxn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginTxnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MTikvCliServer).BeginTxn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtikv_cli.MTikvCli/BeginTxn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MTikvCliServer).BeginTxn(ctx, req.(*BeginTxnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MTikvCli_CommitTxn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitTxnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MTikvCliServer).CommitTxn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtikv_cli.MTikvCli/CommitTxn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MTikvCliServer).CommitTxn(ctx, req.(*CommitTxnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MTikvCli_RollBackTxn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollBackTxnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MTikvCliServer).RollBackTxn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtikv_cli.MTikvCli/RollBackTxn",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MTikvCliServer).RollBackTxn(ctx, req.(*RollBackTxnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MTikvCli_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MTikvCliServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtikv_cli.MTikvCli/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MTikvCliServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MTikvCli_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MTikvCliServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtikv_cli.MTikvCli/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MTikvCliServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MTikvCli_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MTikvCliServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtikv_cli.MTikvCli/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MTikvCliServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MTikvCli_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mtikv_cli.MTikvCli",
	HandlerType: (*MTikvCliServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BeginTxn",
			Handler:    _MTikvCli_BeginTxn_Handler,
		},
		{
			MethodName: "CommitTxn",
			Handler:    _MTikvCli_CommitTxn_Handler,
		},
		{
			MethodName: "RollBackTxn",
			Handler:    _MTikvCli_RollBackTxn_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _MTikvCli_Set_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _MTikvCli_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _MTikvCli_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mtikv_clipb.proto",
}
