// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mtikvpb.proto

package mtikvpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Op int32

const (
	Op_Put Op = 0
	Op_Del Op = 1
)

var Op_name = map[int32]string{
	0: "Put",
	1: "Del",
}

var Op_value = map[string]int32{
	"Put": 0,
	"Del": 1,
}

func (x Op) String() string {
	return proto.EnumName(Op_name, int32(x))
}

func (Op) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{0}
}

type Error int32

const (
	Error_RegionNotFound Error = 0
	Error_KeyNotInRegion Error = 1
)

var Error_name = map[int32]string{
	0: "RegionNotFound",
	1: "KeyNotInRegion",
}

var Error_value = map[string]int32{
	"RegionNotFound": 0,
	"KeyNotInRegion": 1,
}

func (x Error) String() string {
	return proto.EnumName(Error_name, int32(x))
}

func (Error) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{1}
}

type KeyError int32

const (
	KeyError_WriteConflict KeyError = 0
	KeyError_KeyIsLocked   KeyError = 1
)

var KeyError_name = map[int32]string{
	0: "WriteConflict",
	1: "KeyIsLocked",
}

var KeyError_value = map[string]int32{
	"WriteConflict": 0,
	"KeyIsLocked":   1,
}

func (x KeyError) String() string {
	return proto.EnumName(KeyError_name, int32(x))
}

func (KeyError) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{2}
}

type KvPair struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KvPair) Reset()         { *m = KvPair{} }
func (m *KvPair) String() string { return proto.CompactTextString(m) }
func (*KvPair) ProtoMessage()    {}
func (*KvPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{0}
}

func (m *KvPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KvPair.Unmarshal(m, b)
}
func (m *KvPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KvPair.Marshal(b, m, deterministic)
}
func (m *KvPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KvPair.Merge(m, src)
}
func (m *KvPair) XXX_Size() int {
	return xxx_messageInfo_KvPair.Size(m)
}
func (m *KvPair) XXX_DiscardUnknown() {
	xxx_messageInfo_KvPair.DiscardUnknown(m)
}

var xxx_messageInfo_KvPair proto.InternalMessageInfo

func (m *KvPair) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *KvPair) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Mutation struct {
	Op                   Op       `protobuf:"varint,1,opt,name=op,proto3,enum=mtikvpb.Op" json:"op,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mutation) Reset()         { *m = Mutation{} }
func (m *Mutation) String() string { return proto.CompactTextString(m) }
func (*Mutation) ProtoMessage()    {}
func (*Mutation) Descriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{1}
}

func (m *Mutation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mutation.Unmarshal(m, b)
}
func (m *Mutation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mutation.Marshal(b, m, deterministic)
}
func (m *Mutation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mutation.Merge(m, src)
}
func (m *Mutation) XXX_Size() int {
	return xxx_messageInfo_Mutation.Size(m)
}
func (m *Mutation) XXX_DiscardUnknown() {
	xxx_messageInfo_Mutation.DiscardUnknown(m)
}

var xxx_messageInfo_Mutation proto.InternalMessageInfo

func (m *Mutation) GetOp() Op {
	if m != nil {
		return m.Op
	}
	return Op_Put
}

func (m *Mutation) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Mutation) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type PrewriteRequest struct {
	Mutations            []*Mutation `protobuf:"bytes,1,rep,name=mutations,proto3" json:"mutations,omitempty"`
	PrimaryLock          []byte      `protobuf:"bytes,2,opt,name=primary_lock,json=primaryLock,proto3" json:"primary_lock,omitempty"`
	StartVersion         uint64      `protobuf:"varint,3,opt,name=start_version,json=startVersion,proto3" json:"start_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PrewriteRequest) Reset()         { *m = PrewriteRequest{} }
func (m *PrewriteRequest) String() string { return proto.CompactTextString(m) }
func (*PrewriteRequest) ProtoMessage()    {}
func (*PrewriteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{2}
}

func (m *PrewriteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrewriteRequest.Unmarshal(m, b)
}
func (m *PrewriteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrewriteRequest.Marshal(b, m, deterministic)
}
func (m *PrewriteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrewriteRequest.Merge(m, src)
}
func (m *PrewriteRequest) XXX_Size() int {
	return xxx_messageInfo_PrewriteRequest.Size(m)
}
func (m *PrewriteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrewriteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrewriteRequest proto.InternalMessageInfo

func (m *PrewriteRequest) GetMutations() []*Mutation {
	if m != nil {
		return m.Mutations
	}
	return nil
}

func (m *PrewriteRequest) GetPrimaryLock() []byte {
	if m != nil {
		return m.PrimaryLock
	}
	return nil
}

func (m *PrewriteRequest) GetStartVersion() uint64 {
	if m != nil {
		return m.StartVersion
	}
	return 0
}

type PrewriteReponse struct {
	RegionError          Error      `protobuf:"varint,1,opt,name=region_error,json=regionError,proto3,enum=mtikvpb.Error" json:"region_error,omitempty"`
	Errors               []KeyError `protobuf:"varint,2,rep,packed,name=errors,proto3,enum=mtikvpb.KeyError" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PrewriteReponse) Reset()         { *m = PrewriteReponse{} }
func (m *PrewriteReponse) String() string { return proto.CompactTextString(m) }
func (*PrewriteReponse) ProtoMessage()    {}
func (*PrewriteReponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{3}
}

func (m *PrewriteReponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrewriteReponse.Unmarshal(m, b)
}
func (m *PrewriteReponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrewriteReponse.Marshal(b, m, deterministic)
}
func (m *PrewriteReponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrewriteReponse.Merge(m, src)
}
func (m *PrewriteReponse) XXX_Size() int {
	return xxx_messageInfo_PrewriteReponse.Size(m)
}
func (m *PrewriteReponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrewriteReponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrewriteReponse proto.InternalMessageInfo

func (m *PrewriteReponse) GetRegionError() Error {
	if m != nil {
		return m.RegionError
	}
	return Error_RegionNotFound
}

func (m *PrewriteReponse) GetErrors() []KeyError {
	if m != nil {
		return m.Errors
	}
	return nil
}

type CommitRequest struct {
	Keys                 [][]byte `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	CommitVersion        uint64   `protobuf:"varint,2,opt,name=commit_version,json=commitVersion,proto3" json:"commit_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitRequest) Reset()         { *m = CommitRequest{} }
func (m *CommitRequest) String() string { return proto.CompactTextString(m) }
func (*CommitRequest) ProtoMessage()    {}
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{4}
}

func (m *CommitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitRequest.Unmarshal(m, b)
}
func (m *CommitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitRequest.Marshal(b, m, deterministic)
}
func (m *CommitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitRequest.Merge(m, src)
}
func (m *CommitRequest) XXX_Size() int {
	return xxx_messageInfo_CommitRequest.Size(m)
}
func (m *CommitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommitRequest proto.InternalMessageInfo

func (m *CommitRequest) GetKeys() [][]byte {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *CommitRequest) GetCommitVersion() uint64 {
	if m != nil {
		return m.CommitVersion
	}
	return 0
}

type CommitReponse struct {
	RegionError          Error      `protobuf:"varint,1,opt,name=region_error,json=regionError,proto3,enum=mtikvpb.Error" json:"region_error,omitempty"`
	Errors               []KeyError `protobuf:"varint,2,rep,packed,name=errors,proto3,enum=mtikvpb.KeyError" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CommitReponse) Reset()         { *m = CommitReponse{} }
func (m *CommitReponse) String() string { return proto.CompactTextString(m) }
func (*CommitReponse) ProtoMessage()    {}
func (*CommitReponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{5}
}

func (m *CommitReponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitReponse.Unmarshal(m, b)
}
func (m *CommitReponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitReponse.Marshal(b, m, deterministic)
}
func (m *CommitReponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitReponse.Merge(m, src)
}
func (m *CommitReponse) XXX_Size() int {
	return xxx_messageInfo_CommitReponse.Size(m)
}
func (m *CommitReponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitReponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommitReponse proto.InternalMessageInfo

func (m *CommitReponse) GetRegionError() Error {
	if m != nil {
		return m.RegionError
	}
	return Error_RegionNotFound
}

func (m *CommitReponse) GetErrors() []KeyError {
	if m != nil {
		return m.Errors
	}
	return nil
}

type GetRequest struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Version              uint64   `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{6}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *GetRequest) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

type GetReponse struct {
	RegionError          Error    `protobuf:"varint,1,opt,name=region_error,json=regionError,proto3,enum=mtikvpb.Error" json:"region_error,omitempty"`
	Error                KeyError `protobuf:"varint,2,opt,name=error,proto3,enum=mtikvpb.KeyError" json:"error,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	NotFound             bool     `protobuf:"varint,4,opt,name=not_found,json=notFound,proto3" json:"not_found,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReponse) Reset()         { *m = GetReponse{} }
func (m *GetReponse) String() string { return proto.CompactTextString(m) }
func (*GetReponse) ProtoMessage()    {}
func (*GetReponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{7}
}

func (m *GetReponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReponse.Unmarshal(m, b)
}
func (m *GetReponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReponse.Marshal(b, m, deterministic)
}
func (m *GetReponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReponse.Merge(m, src)
}
func (m *GetReponse) XXX_Size() int {
	return xxx_messageInfo_GetReponse.Size(m)
}
func (m *GetReponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetReponse proto.InternalMessageInfo

func (m *GetReponse) GetRegionError() Error {
	if m != nil {
		return m.RegionError
	}
	return Error_RegionNotFound
}

func (m *GetReponse) GetError() KeyError {
	if m != nil {
		return m.Error
	}
	return KeyError_WriteConflict
}

func (m *GetReponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *GetReponse) GetNotFound() bool {
	if m != nil {
		return m.NotFound
	}
	return false
}

type ResolveLockRequest struct {
	StartVersion         uint64   `protobuf:"varint,1,opt,name=start_version,json=startVersion,proto3" json:"start_version,omitempty"`
	CommitVersion        uint64   `protobuf:"varint,2,opt,name=commit_version,json=commitVersion,proto3" json:"commit_version,omitempty"`
	Keys                 [][]byte `protobuf:"bytes,3,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResolveLockRequest) Reset()         { *m = ResolveLockRequest{} }
func (m *ResolveLockRequest) String() string { return proto.CompactTextString(m) }
func (*ResolveLockRequest) ProtoMessage()    {}
func (*ResolveLockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{8}
}

func (m *ResolveLockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolveLockRequest.Unmarshal(m, b)
}
func (m *ResolveLockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolveLockRequest.Marshal(b, m, deterministic)
}
func (m *ResolveLockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolveLockRequest.Merge(m, src)
}
func (m *ResolveLockRequest) XXX_Size() int {
	return xxx_messageInfo_ResolveLockRequest.Size(m)
}
func (m *ResolveLockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolveLockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResolveLockRequest proto.InternalMessageInfo

func (m *ResolveLockRequest) GetStartVersion() uint64 {
	if m != nil {
		return m.StartVersion
	}
	return 0
}

func (m *ResolveLockRequest) GetCommitVersion() uint64 {
	if m != nil {
		return m.CommitVersion
	}
	return 0
}

func (m *ResolveLockRequest) GetKeys() [][]byte {
	if m != nil {
		return m.Keys
	}
	return nil
}

type ResolveLockResponse struct {
	RegionError          Error    `protobuf:"varint,1,opt,name=region_error,json=regionError,proto3,enum=mtikvpb.Error" json:"region_error,omitempty"`
	Error                KeyError `protobuf:"varint,2,opt,name=error,proto3,enum=mtikvpb.KeyError" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResolveLockResponse) Reset()         { *m = ResolveLockResponse{} }
func (m *ResolveLockResponse) String() string { return proto.CompactTextString(m) }
func (*ResolveLockResponse) ProtoMessage()    {}
func (*ResolveLockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{9}
}

func (m *ResolveLockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolveLockResponse.Unmarshal(m, b)
}
func (m *ResolveLockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolveLockResponse.Marshal(b, m, deterministic)
}
func (m *ResolveLockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolveLockResponse.Merge(m, src)
}
func (m *ResolveLockResponse) XXX_Size() int {
	return xxx_messageInfo_ResolveLockResponse.Size(m)
}
func (m *ResolveLockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolveLockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResolveLockResponse proto.InternalMessageInfo

func (m *ResolveLockResponse) GetRegionError() Error {
	if m != nil {
		return m.RegionError
	}
	return Error_RegionNotFound
}

func (m *ResolveLockResponse) GetError() KeyError {
	if m != nil {
		return m.Error
	}
	return KeyError_WriteConflict
}

type GCRequest struct {
	SafePoint            uint64   `protobuf:"varint,1,opt,name=safe_point,json=safePoint,proto3" json:"safe_point,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GCRequest) Reset()         { *m = GCRequest{} }
func (m *GCRequest) String() string { return proto.CompactTextString(m) }
func (*GCRequest) ProtoMessage()    {}
func (*GCRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{10}
}

func (m *GCRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GCRequest.Unmarshal(m, b)
}
func (m *GCRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GCRequest.Marshal(b, m, deterministic)
}
func (m *GCRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GCRequest.Merge(m, src)
}
func (m *GCRequest) XXX_Size() int {
	return xxx_messageInfo_GCRequest.Size(m)
}
func (m *GCRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GCRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GCRequest proto.InternalMessageInfo

func (m *GCRequest) GetSafePoint() uint64 {
	if m != nil {
		return m.SafePoint
	}
	return 0
}

type GCResponse struct {
	RegionError          Error    `protobuf:"varint,1,opt,name=region_error,json=regionError,proto3,enum=mtikvpb.Error" json:"region_error,omitempty"`
	Error                KeyError `protobuf:"varint,2,opt,name=error,proto3,enum=mtikvpb.KeyError" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GCResponse) Reset()         { *m = GCResponse{} }
func (m *GCResponse) String() string { return proto.CompactTextString(m) }
func (*GCResponse) ProtoMessage()    {}
func (*GCResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{11}
}

func (m *GCResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GCResponse.Unmarshal(m, b)
}
func (m *GCResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GCResponse.Marshal(b, m, deterministic)
}
func (m *GCResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GCResponse.Merge(m, src)
}
func (m *GCResponse) XXX_Size() int {
	return xxx_messageInfo_GCResponse.Size(m)
}
func (m *GCResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GCResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GCResponse proto.InternalMessageInfo

func (m *GCResponse) GetRegionError() Error {
	if m != nil {
		return m.RegionError
	}
	return Error_RegionNotFound
}

func (m *GCResponse) GetError() KeyError {
	if m != nil {
		return m.Error
	}
	return KeyError_WriteConflict
}

type RawGetRequest struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Cf                   string   `protobuf:"bytes,2,opt,name=cf,proto3" json:"cf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawGetRequest) Reset()         { *m = RawGetRequest{} }
func (m *RawGetRequest) String() string { return proto.CompactTextString(m) }
func (*RawGetRequest) ProtoMessage()    {}
func (*RawGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{12}
}

func (m *RawGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawGetRequest.Unmarshal(m, b)
}
func (m *RawGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawGetRequest.Marshal(b, m, deterministic)
}
func (m *RawGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawGetRequest.Merge(m, src)
}
func (m *RawGetRequest) XXX_Size() int {
	return xxx_messageInfo_RawGetRequest.Size(m)
}
func (m *RawGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RawGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RawGetRequest proto.InternalMessageInfo

func (m *RawGetRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *RawGetRequest) GetCf() string {
	if m != nil {
		return m.Cf
	}
	return ""
}

type RawGetResponse struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	NotFound             bool     `protobuf:"varint,2,opt,name=not_found,json=notFound,proto3" json:"not_found,omitempty"`
	RegionError          Error    `protobuf:"varint,3,opt,name=region_error,json=regionError,proto3,enum=mtikvpb.Error" json:"region_error,omitempty"`
	Error                KeyError `protobuf:"varint,4,opt,name=error,proto3,enum=mtikvpb.KeyError" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawGetResponse) Reset()         { *m = RawGetResponse{} }
func (m *RawGetResponse) String() string { return proto.CompactTextString(m) }
func (*RawGetResponse) ProtoMessage()    {}
func (*RawGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{13}
}

func (m *RawGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawGetResponse.Unmarshal(m, b)
}
func (m *RawGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawGetResponse.Marshal(b, m, deterministic)
}
func (m *RawGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawGetResponse.Merge(m, src)
}
func (m *RawGetResponse) XXX_Size() int {
	return xxx_messageInfo_RawGetResponse.Size(m)
}
func (m *RawGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RawGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RawGetResponse proto.InternalMessageInfo

func (m *RawGetResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *RawGetResponse) GetNotFound() bool {
	if m != nil {
		return m.NotFound
	}
	return false
}

func (m *RawGetResponse) GetRegionError() Error {
	if m != nil {
		return m.RegionError
	}
	return Error_RegionNotFound
}

func (m *RawGetResponse) GetError() KeyError {
	if m != nil {
		return m.Error
	}
	return KeyError_WriteConflict
}

type RawPutRequest struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Cf                   string   `protobuf:"bytes,3,opt,name=cf,proto3" json:"cf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawPutRequest) Reset()         { *m = RawPutRequest{} }
func (m *RawPutRequest) String() string { return proto.CompactTextString(m) }
func (*RawPutRequest) ProtoMessage()    {}
func (*RawPutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{14}
}

func (m *RawPutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawPutRequest.Unmarshal(m, b)
}
func (m *RawPutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawPutRequest.Marshal(b, m, deterministic)
}
func (m *RawPutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawPutRequest.Merge(m, src)
}
func (m *RawPutRequest) XXX_Size() int {
	return xxx_messageInfo_RawPutRequest.Size(m)
}
func (m *RawPutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RawPutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RawPutRequest proto.InternalMessageInfo

func (m *RawPutRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *RawPutRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *RawPutRequest) GetCf() string {
	if m != nil {
		return m.Cf
	}
	return ""
}

type RawPutResponse struct {
	RegionError          Error    `protobuf:"varint,1,opt,name=region_error,json=regionError,proto3,enum=mtikvpb.Error" json:"region_error,omitempty"`
	Error                KeyError `protobuf:"varint,2,opt,name=error,proto3,enum=mtikvpb.KeyError" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawPutResponse) Reset()         { *m = RawPutResponse{} }
func (m *RawPutResponse) String() string { return proto.CompactTextString(m) }
func (*RawPutResponse) ProtoMessage()    {}
func (*RawPutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{15}
}

func (m *RawPutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawPutResponse.Unmarshal(m, b)
}
func (m *RawPutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawPutResponse.Marshal(b, m, deterministic)
}
func (m *RawPutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawPutResponse.Merge(m, src)
}
func (m *RawPutResponse) XXX_Size() int {
	return xxx_messageInfo_RawPutResponse.Size(m)
}
func (m *RawPutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RawPutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RawPutResponse proto.InternalMessageInfo

func (m *RawPutResponse) GetRegionError() Error {
	if m != nil {
		return m.RegionError
	}
	return Error_RegionNotFound
}

func (m *RawPutResponse) GetError() KeyError {
	if m != nil {
		return m.Error
	}
	return KeyError_WriteConflict
}

type RawDeleteRequest struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Cf                   string   `protobuf:"bytes,2,opt,name=cf,proto3" json:"cf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawDeleteRequest) Reset()         { *m = RawDeleteRequest{} }
func (m *RawDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*RawDeleteRequest) ProtoMessage()    {}
func (*RawDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{16}
}

func (m *RawDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawDeleteRequest.Unmarshal(m, b)
}
func (m *RawDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawDeleteRequest.Marshal(b, m, deterministic)
}
func (m *RawDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawDeleteRequest.Merge(m, src)
}
func (m *RawDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_RawDeleteRequest.Size(m)
}
func (m *RawDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RawDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RawDeleteRequest proto.InternalMessageInfo

func (m *RawDeleteRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *RawDeleteRequest) GetCf() string {
	if m != nil {
		return m.Cf
	}
	return ""
}

type RawDeleteResponse struct {
	RegionError          Error    `protobuf:"varint,1,opt,name=region_error,json=regionError,proto3,enum=mtikvpb.Error" json:"region_error,omitempty"`
	Error                KeyError `protobuf:"varint,2,opt,name=error,proto3,enum=mtikvpb.KeyError" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawDeleteResponse) Reset()         { *m = RawDeleteResponse{} }
func (m *RawDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*RawDeleteResponse) ProtoMessage()    {}
func (*RawDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{17}
}

func (m *RawDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawDeleteResponse.Unmarshal(m, b)
}
func (m *RawDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawDeleteResponse.Marshal(b, m, deterministic)
}
func (m *RawDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawDeleteResponse.Merge(m, src)
}
func (m *RawDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_RawDeleteResponse.Size(m)
}
func (m *RawDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RawDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RawDeleteResponse proto.InternalMessageInfo

func (m *RawDeleteResponse) GetRegionError() Error {
	if m != nil {
		return m.RegionError
	}
	return Error_RegionNotFound
}

func (m *RawDeleteResponse) GetError() KeyError {
	if m != nil {
		return m.Error
	}
	return KeyError_WriteConflict
}

func init() {
	proto.RegisterEnum("mtikvpb.Op", Op_name, Op_value)
	proto.RegisterEnum("mtikvpb.Error", Error_name, Error_value)
	proto.RegisterEnum("mtikvpb.KeyError", KeyError_name, KeyError_value)
	proto.RegisterType((*KvPair)(nil), "mtikvpb.KvPair")
	proto.RegisterType((*Mutation)(nil), "mtikvpb.Mutation")
	proto.RegisterType((*PrewriteRequest)(nil), "mtikvpb.PrewriteRequest")
	proto.RegisterType((*PrewriteReponse)(nil), "mtikvpb.PrewriteReponse")
	proto.RegisterType((*CommitRequest)(nil), "mtikvpb.CommitRequest")
	proto.RegisterType((*CommitReponse)(nil), "mtikvpb.CommitReponse")
	proto.RegisterType((*GetRequest)(nil), "mtikvpb.GetRequest")
	proto.RegisterType((*GetReponse)(nil), "mtikvpb.GetReponse")
	proto.RegisterType((*ResolveLockRequest)(nil), "mtikvpb.ResolveLockRequest")
	proto.RegisterType((*ResolveLockResponse)(nil), "mtikvpb.ResolveLockResponse")
	proto.RegisterType((*GCRequest)(nil), "mtikvpb.GCRequest")
	proto.RegisterType((*GCResponse)(nil), "mtikvpb.GCResponse")
	proto.RegisterType((*RawGetRequest)(nil), "mtikvpb.RawGetRequest")
	proto.RegisterType((*RawGetResponse)(nil), "mtikvpb.RawGetResponse")
	proto.RegisterType((*RawPutRequest)(nil), "mtikvpb.RawPutRequest")
	proto.RegisterType((*RawPutResponse)(nil), "mtikvpb.RawPutResponse")
	proto.RegisterType((*RawDeleteRequest)(nil), "mtikvpb.RawDeleteRequest")
	proto.RegisterType((*RawDeleteResponse)(nil), "mtikvpb.RawDeleteResponse")
}

func init() { proto.RegisterFile("mtikvpb.proto", fileDescriptor_185c3bb479740444) }

var fileDescriptor_185c3bb479740444 = []byte{
	// 788 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0x4d, 0x6f, 0xda, 0x4a,
	0x14, 0xc5, 0x36, 0x10, 0xb8, 0x7c, 0x84, 0x4c, 0x9e, 0xf2, 0x78, 0x4e, 0x9e, 0xc4, 0xf3, 0x53,
	0x55, 0xca, 0x22, 0x34, 0x49, 0x17, 0x95, 0xda, 0x55, 0x48, 0x8b, 0x52, 0xe7, 0x03, 0xb9, 0x55,
	0xbb, 0x44, 0x0e, 0x19, 0x52, 0x0b, 0xe3, 0x71, 0xec, 0xc1, 0x11, 0x7f, 0xa0, 0x8b, 0xfe, 0x85,
	0x2e, 0xfa, 0x57, 0x2b, 0xcf, 0x78, 0x8c, 0x1d, 0xbb, 0x49, 0x5b, 0x29, 0xd9, 0x79, 0xee, 0x9c,
	0x7b, 0xe6, 0x1c, 0xee, 0x9d, 0x3b, 0x40, 0x63, 0x4e, 0xad, 0x59, 0xe0, 0x5e, 0xec, 0xba, 0x1e,
	0xa1, 0x04, 0xad, 0x45, 0x4b, 0x75, 0xe7, 0x8a, 0x90, 0x2b, 0x1b, 0xf7, 0x4d, 0xd7, 0xea, 0x9b,
	0x8e, 0x43, 0xa8, 0x49, 0x2d, 0xe2, 0xf8, 0x1c, 0xa6, 0x3d, 0x87, 0xb2, 0x1e, 0x8c, 0x4c, 0xcb,
	0x43, 0x2d, 0x50, 0x66, 0x78, 0xd9, 0x96, 0x3a, 0x52, 0xb7, 0x6e, 0x84, 0x9f, 0xe8, 0x2f, 0x28,
	0x05, 0xa6, 0xbd, 0xc0, 0x6d, 0x99, 0xc5, 0xf8, 0x42, 0x3b, 0x87, 0xca, 0xe9, 0x82, 0x93, 0xa0,
	0x6d, 0x90, 0x89, 0xcb, 0x52, 0x9a, 0xfb, 0xb5, 0x5d, 0x21, 0xe0, 0xdc, 0x35, 0x64, 0xe2, 0x0a,
	0x42, 0x39, 0x87, 0x50, 0x49, 0x12, 0x7e, 0x95, 0x60, 0x7d, 0xe4, 0xe1, 0x1b, 0xcf, 0xa2, 0xd8,
	0xc0, 0xd7, 0x0b, 0xec, 0x53, 0xd4, 0x87, 0xea, 0x3c, 0x3a, 0xc4, 0x6f, 0x4b, 0x1d, 0xa5, 0x5b,
	0xdb, 0xdf, 0x88, 0xf9, 0xc5, 0xf1, 0xc6, 0x0a, 0x83, 0xfe, 0x83, 0xba, 0xeb, 0x59, 0x73, 0xd3,
	0x5b, 0x8e, 0x6d, 0x32, 0x99, 0x45, 0xa7, 0xd6, 0xa2, 0xd8, 0x09, 0x99, 0xcc, 0xd0, 0xff, 0xd0,
	0xf0, 0xa9, 0xe9, 0xd1, 0x71, 0x80, 0x3d, 0xdf, 0x22, 0x0e, 0x53, 0x51, 0x34, 0xea, 0x2c, 0xf8,
	0x91, 0xc7, 0x34, 0x92, 0xd4, 0xe2, 0x12, 0xc7, 0xc7, 0x68, 0x0f, 0xea, 0x1e, 0xbe, 0xb2, 0x88,
	0x33, 0xc6, 0x9e, 0x47, 0xbc, 0xc8, 0x6e, 0x33, 0x96, 0xf3, 0x26, 0x8c, 0x1a, 0x35, 0x8e, 0x61,
	0x0b, 0xf4, 0x0c, 0xca, 0x0c, 0xeb, 0xb7, 0xe5, 0x8e, 0xd2, 0x6d, 0x26, 0xb4, 0xeb, 0x78, 0xc9,
	0xf1, 0x11, 0x40, 0x7b, 0x07, 0x8d, 0x01, 0x99, 0xcf, 0x2d, 0x2a, 0xac, 0x23, 0x28, 0xce, 0xf0,
	0x92, 0xbb, 0xae, 0x1b, 0xec, 0x1b, 0x3d, 0x81, 0xe6, 0x84, 0x81, 0x62, 0xed, 0x32, 0xd3, 0xde,
	0xe0, 0x51, 0x21, 0x7e, 0xbe, 0xe2, 0x7a, 0x0c, 0xe9, 0x2f, 0x01, 0x86, 0x38, 0xd6, 0x9d, 0xed,
	0x9f, 0x36, 0xac, 0xa5, 0xe5, 0x8a, 0xa5, 0xf6, 0x4d, 0x8a, 0x52, 0xff, 0x58, 0xe6, 0x53, 0x28,
	0x71, 0xac, 0xcc, 0xb0, 0x39, 0x2a, 0xf9, 0x7e, 0x7e, 0xcf, 0xa1, 0x6d, 0xa8, 0x3a, 0x84, 0x8e,
	0xa7, 0x64, 0xe1, 0x5c, 0xb6, 0x8b, 0x1d, 0xa9, 0x5b, 0x31, 0x2a, 0x0e, 0xa1, 0x6f, 0xc3, 0xb5,
	0x46, 0x01, 0x19, 0xd8, 0x27, 0x76, 0x80, 0xc3, 0xbe, 0x11, 0xfe, 0x32, 0xed, 0x23, 0x65, 0xdb,
	0xe7, 0x17, 0x0b, 0x15, 0xd7, 0x58, 0x59, 0xd5, 0x58, 0xbb, 0x86, 0xcd, 0xd4, 0xa9, 0xfe, 0x83,
	0xff, 0x36, 0x5a, 0x0f, 0xaa, 0xc3, 0x81, 0xf0, 0xf7, 0x2f, 0x80, 0x6f, 0x4e, 0xf1, 0xd8, 0x25,
	0x96, 0x43, 0x23, 0x73, 0xd5, 0x30, 0x32, 0x0a, 0x03, 0xda, 0x67, 0x80, 0x10, 0xfb, 0x08, 0xaa,
	0xf6, 0xa0, 0x61, 0x98, 0x37, 0x77, 0x76, 0x56, 0x13, 0xe4, 0xc9, 0x94, 0x11, 0x55, 0x0d, 0x79,
	0x32, 0xd5, 0xbe, 0x4b, 0xd0, 0x14, 0x39, 0x91, 0xc2, 0xb8, 0xee, 0xd2, 0x4f, 0xeb, 0x2e, 0xa7,
	0xeb, 0x9e, 0x31, 0xa5, 0xfc, 0x86, 0xa9, 0xe2, 0x3d, 0xa6, 0x86, 0xcc, 0xd4, 0x68, 0x71, 0x87,
	0xa9, 0xdc, 0x71, 0x1b, 0x59, 0x55, 0x62, 0xab, 0x36, 0x73, 0xca, 0x88, 0x1e, 0xa1, 0x16, 0x2f,
	0xa0, 0x65, 0x98, 0x37, 0x47, 0xd8, 0xc6, 0xab, 0xd9, 0x7c, 0x7f, 0x39, 0x08, 0x6c, 0x24, 0xb2,
	0x1e, 0x5e, 0x66, 0x6f, 0x0b, 0xe4, 0x73, 0x17, 0xad, 0x81, 0x32, 0x5a, 0xd0, 0x56, 0x21, 0xfc,
	0x38, 0xc2, 0x76, 0x4b, 0xea, 0xf5, 0xa1, 0xc4, 0x99, 0x10, 0x34, 0x0d, 0x46, 0x7c, 0x16, 0x15,
	0xbb, 0x55, 0x08, 0x63, 0x3a, 0x5e, 0x9e, 0x11, 0x7a, 0xec, 0xf0, 0xbd, 0x96, 0xd4, 0xdb, 0x85,
	0x8a, 0xe0, 0x46, 0x1b, 0xd0, 0xf8, 0x14, 0xbe, 0x03, 0x03, 0xe2, 0x4c, 0x6d, 0x6b, 0x12, 0x12,
	0xaf, 0x43, 0x4d, 0xc7, 0xcb, 0x63, 0x3f, 0xbc, 0xa1, 0xf8, 0xb2, 0x25, 0xed, 0x7f, 0x29, 0x42,
	0xfd, 0xf4, 0x83, 0xa5, 0x07, 0xef, 0xb1, 0x17, 0x58, 0x13, 0x8c, 0x0e, 0x01, 0xf4, 0x40, 0xbc,
	0x20, 0xa8, 0x1d, 0x2b, 0xbe, 0xf5, 0xc0, 0xa9, 0x79, 0x3b, 0xec, 0x77, 0xd2, 0x0a, 0xe8, 0x35,
	0x54, 0xf4, 0x80, 0x0f, 0x72, 0xb4, 0x15, 0xe3, 0x52, 0xaf, 0x84, 0x9a, 0x8d, 0x8b, 0xec, 0x03,
	0x28, 0xe9, 0xc1, 0x10, 0x53, 0xb4, 0x19, 0x43, 0x56, 0x77, 0x49, 0xbd, 0x15, 0x14, 0x49, 0x27,
	0xd0, 0xd0, 0x83, 0xc4, 0xf8, 0x41, 0xdb, 0x31, 0x2e, 0x3b, 0x0a, 0xd5, 0x9d, 0xfc, 0x4d, 0x5f,
	0xb0, 0xed, 0x41, 0x51, 0x0f, 0x86, 0x03, 0x84, 0x56, 0x87, 0x0d, 0xee, 0x11, 0xf0, 0x0a, 0xca,
	0xfc, 0x02, 0x27, 0x1c, 0xa7, 0xa6, 0x80, 0xfa, 0x77, 0x26, 0xee, 0xa7, 0x93, 0x47, 0x8b, 0x5b,
	0xc9, 0xab, 0xdb, 0x96, 0x4e, 0x4e, 0x5c, 0x1e, 0xad, 0x80, 0x8e, 0xa0, 0x1a, 0x37, 0x2b, 0xfa,
	0x27, 0x89, 0x4b, 0xb5, 0xbd, 0xaa, 0xe6, 0x6d, 0x09, 0x96, 0xc3, 0x2a, 0x94, 0xd8, 0xf6, 0x48,
	0xba, 0x28, 0xb3, 0x7f, 0x56, 0x07, 0x3f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xfd, 0x74, 0x45, 0xbc,
	0x91, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MTiKvServiceClient is the client API for MTiKvService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MTiKvServiceClient interface {
	KvPrewrite(ctx context.Context, in *PrewriteRequest, opts ...grpc.CallOption) (*PrewriteReponse, error)
	KvCommit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitReponse, error)
	KvGet(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReponse, error)
	KvResolveLock(ctx context.Context, in *ResolveLockRequest, opts ...grpc.CallOption) (*ResolveLockResponse, error)
	KvGC(ctx context.Context, in *GCRequest, opts ...grpc.CallOption) (*GetReponse, error)
	RawGet(ctx context.Context, in *RawGetRequest, opts ...grpc.CallOption) (*RawGetResponse, error)
	RawPut(ctx context.Context, in *RawPutRequest, opts ...grpc.CallOption) (*RawPutResponse, error)
	RawDelete(ctx context.Context, in *RawDeleteRequest, opts ...grpc.CallOption) (*RawDeleteResponse, error)
}

type mTiKvServiceClient struct {
	cc *grpc.ClientConn
}

func NewMTiKvServiceClient(cc *grpc.ClientConn) MTiKvServiceClient {
	return &mTiKvServiceClient{cc}
}

func (c *mTiKvServiceClient) KvPrewrite(ctx context.Context, in *PrewriteRequest, opts ...grpc.CallOption) (*PrewriteReponse, error) {
	out := new(PrewriteReponse)
	err := c.cc.Invoke(ctx, "/mtikvpb.MTiKvService/KvPrewrite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mTiKvServiceClient) KvCommit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitReponse, error) {
	out := new(CommitReponse)
	err := c.cc.Invoke(ctx, "/mtikvpb.MTiKvService/KvCommit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mTiKvServiceClient) KvGet(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReponse, error) {
	out := new(GetReponse)
	err := c.cc.Invoke(ctx, "/mtikvpb.MTiKvService/KvGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mTiKvServiceClient) KvResolveLock(ctx context.Context, in *ResolveLockRequest, opts ...grpc.CallOption) (*ResolveLockResponse, error) {
	out := new(ResolveLockResponse)
	err := c.cc.Invoke(ctx, "/mtikvpb.MTiKvService/KvResolveLock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mTiKvServiceClient) KvGC(ctx context.Context, in *GCRequest, opts ...grpc.CallOption) (*GetReponse, error) {
	out := new(GetReponse)
	err := c.cc.Invoke(ctx, "/mtikvpb.MTiKvService/KvGC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mTiKvServiceClient) RawGet(ctx context.Context, in *RawGetRequest, opts ...grpc.CallOption) (*RawGetResponse, error) {
	out := new(RawGetResponse)
	err := c.cc.Invoke(ctx, "/mtikvpb.MTiKvService/RawGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mTiKvServiceClient) RawPut(ctx context.Context, in *RawPutRequest, opts ...grpc.CallOption) (*RawPutResponse, error) {
	out := new(RawPutResponse)
	err := c.cc.Invoke(ctx, "/mtikvpb.MTiKvService/RawPut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mTiKvServiceClient) RawDelete(ctx context.Context, in *RawDeleteRequest, opts ...grpc.CallOption) (*RawDeleteResponse, error) {
	out := new(RawDeleteResponse)
	err := c.cc.Invoke(ctx, "/mtikvpb.MTiKvService/RawDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MTiKvServiceServer is the server API for MTiKvService service.
type MTiKvServiceServer interface {
	KvPrewrite(context.Context, *PrewriteRequest) (*PrewriteReponse, error)
	KvCommit(context.Context, *CommitRequest) (*CommitReponse, error)
	KvGet(context.Context, *GetRequest) (*GetReponse, error)
	KvResolveLock(context.Context, *ResolveLockRequest) (*ResolveLockResponse, error)
	KvGC(context.Context, *GCRequest) (*GetReponse, error)
	RawGet(context.Context, *RawGetRequest) (*RawGetResponse, error)
	RawPut(context.Context, *RawPutRequest) (*RawPutResponse, error)
	RawDelete(context.Context, *RawDeleteRequest) (*RawDeleteResponse, error)
}

// UnimplementedMTiKvServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMTiKvServiceServer struct {
}

func (*UnimplementedMTiKvServiceServer) KvPrewrite(ctx context.Context, req *PrewriteRequest) (*PrewriteReponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KvPrewrite not implemented")
}
func (*UnimplementedMTiKvServiceServer) KvCommit(ctx context.Context, req *CommitRequest) (*CommitReponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KvCommit not implemented")
}
func (*UnimplementedMTiKvServiceServer) KvGet(ctx context.Context, req *GetRequest) (*GetReponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KvGet not implemented")
}
func (*UnimplementedMTiKvServiceServer) KvResolveLock(ctx context.Context, req *ResolveLockRequest) (*ResolveLockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KvResolveLock not implemented")
}
func (*UnimplementedMTiKvServiceServer) KvGC(ctx context.Context, req *GCRequest) (*GetReponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KvGC not implemented")
}
func (*UnimplementedMTiKvServiceServer) RawGet(ctx context.Context, req *RawGetRequest) (*RawGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RawGet not implemented")
}
func (*UnimplementedMTiKvServiceServer) RawPut(ctx context.Context, req *RawPutRequest) (*RawPutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RawPut not implemented")
}
func (*UnimplementedMTiKvServiceServer) RawDelete(ctx context.Context, req *RawDeleteRequest) (*RawDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RawDelete not implemented")
}

func RegisterMTiKvServiceServer(s *grpc.Server, srv MTiKvServiceServer) {
	s.RegisterService(&_MTiKvService_serviceDesc, srv)
}

func _MTiKvService_KvPrewrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrewriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MTiKvServiceServer).KvPrewrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtikvpb.MTiKvService/KvPrewrite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MTiKvServiceServer).KvPrewrite(ctx, req.(*PrewriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MTiKvService_KvCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MTiKvServiceServer).KvCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtikvpb.MTiKvService/KvCommit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MTiKvServiceServer).KvCommit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MTiKvService_KvGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MTiKvServiceServer).KvGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtikvpb.MTiKvService/KvGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MTiKvServiceServer).KvGet(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MTiKvService_KvResolveLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveLockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MTiKvServiceServer).KvResolveLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtikvpb.MTiKvService/KvResolveLock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MTiKvServiceServer).KvResolveLock(ctx, req.(*ResolveLockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MTiKvService_KvGC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MTiKvServiceServer).KvGC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtikvpb.MTiKvService/KvGC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MTiKvServiceServer).KvGC(ctx, req.(*GCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MTiKvService_RawGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MTiKvServiceServer).RawGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtikvpb.MTiKvService/RawGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MTiKvServiceServer).RawGet(ctx, req.(*RawGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MTiKvService_RawPut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawPutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MTiKvServiceServer).RawPut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtikvpb.MTiKvService/RawPut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MTiKvServiceServer).RawPut(ctx, req.(*RawPutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MTiKvService_RawDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MTiKvServiceServer).RawDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtikvpb.MTiKvService/RawDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MTiKvServiceServer).RawDelete(ctx, req.(*RawDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MTiKvService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mtikvpb.MTiKvService",
	HandlerType: (*MTiKvServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "KvPrewrite",
			Handler:    _MTiKvService_KvPrewrite_Handler,
		},
		{
			MethodName: "KvCommit",
			Handler:    _MTiKvService_KvCommit_Handler,
		},
		{
			MethodName: "KvGet",
			Handler:    _MTiKvService_KvGet_Handler,
		},
		{
			MethodName: "KvResolveLock",
			Handler:    _MTiKvService_KvResolveLock_Handler,
		},
		{
			MethodName: "KvGC",
			Handler:    _MTiKvService_KvGC_Handler,
		},
		{
			MethodName: "RawGet",
			Handler:    _MTiKvService_RawGet_Handler,
		},
		{
			MethodName: "RawPut",
			Handler:    _MTiKvService_RawPut_Handler,
		},
		{
			MethodName: "RawDelete",
			Handler:    _MTiKvService_RawDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mtikvpb.proto",
}
