// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mtikvpb.proto

package mtikvpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Op int32

const (
	Op_DEL   Op = 0
	Op_PUT   Op = 1
	Op_RBACK Op = 2
)

var Op_name = map[int32]string{
	0: "DEL",
	1: "PUT",
	2: "RBACK",
}

var Op_value = map[string]int32{
	"DEL":   0,
	"PUT":   1,
	"RBACK": 2,
}

func (x Op) String() string {
	return proto.EnumName(Op_name, int32(x))
}

func (Op) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{0}
}

type MvccOp int32

const (
	MvccOp_NULL   MvccOp = 0
	MvccOp_PRWITE MvccOp = 1
	MvccOp_COMMIT MvccOp = 2
)

var MvccOp_name = map[int32]string{
	0: "NULL",
	1: "PRWITE",
	2: "COMMIT",
}

var MvccOp_value = map[string]int32{
	"NULL":   0,
	"PRWITE": 1,
	"COMMIT": 2,
}

func (x MvccOp) String() string {
	return proto.EnumName(MvccOp_name, int32(x))
}

func (MvccOp) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{1}
}

type Error int32

const (
	Error_RegionNotFound Error = 0
	Error_KeyNotInRegion Error = 1
)

var Error_name = map[int32]string{
	0: "RegionNotFound",
	1: "KeyNotInRegion",
}

var Error_value = map[string]int32{
	"RegionNotFound": 0,
	"KeyNotInRegion": 1,
}

func (x Error) String() string {
	return proto.EnumName(Error_name, int32(x))
}

func (Error) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{2}
}

type KeyError int32

const (
	KeyError_WriteConflict KeyError = 0
	KeyError_KeyIsLocked   KeyError = 1
)

var KeyError_name = map[int32]string{
	0: "WriteConflict",
	1: "KeyIsLocked",
}

var KeyError_value = map[string]int32{
	"WriteConflict": 0,
	"KeyIsLocked":   1,
}

func (x KeyError) String() string {
	return proto.EnumName(KeyError_name, int32(x))
}

func (KeyError) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{3}
}

type MvccObject struct {
	Op                   Op       `protobuf:"varint,1,opt,name=op,proto3,enum=mtikvpb.Op" json:"op,omitempty"`
	Cf                   int32    `protobuf:"varint,2,opt,name=cf,proto3" json:"cf,omitempty"`
	Key                  []byte   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	PrimaryKey           []byte   `protobuf:"bytes,5,opt,name=primary_key,json=primaryKey,proto3" json:"primary_key,omitempty"`
	StartTs              uint64   `protobuf:"varint,6,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	CommitTs             uint64   `protobuf:"varint,7,opt,name=commit_ts,json=commitTs,proto3" json:"commit_ts,omitempty"`
	LatestCommit         uint64   `protobuf:"varint,8,opt,name=latest_commit,json=latestCommit,proto3" json:"latest_commit,omitempty"`
	MvccOp               MvccOp   `protobuf:"varint,9,opt,name=mvcc_op,json=mvccOp,proto3,enum=mtikvpb.MvccOp" json:"mvcc_op,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MvccObject) Reset()         { *m = MvccObject{} }
func (m *MvccObject) String() string { return proto.CompactTextString(m) }
func (*MvccObject) ProtoMessage()    {}
func (*MvccObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{0}
}

func (m *MvccObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MvccObject.Unmarshal(m, b)
}
func (m *MvccObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MvccObject.Marshal(b, m, deterministic)
}
func (m *MvccObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MvccObject.Merge(m, src)
}
func (m *MvccObject) XXX_Size() int {
	return xxx_messageInfo_MvccObject.Size(m)
}
func (m *MvccObject) XXX_DiscardUnknown() {
	xxx_messageInfo_MvccObject.DiscardUnknown(m)
}

var xxx_messageInfo_MvccObject proto.InternalMessageInfo

func (m *MvccObject) GetOp() Op {
	if m != nil {
		return m.Op
	}
	return Op_DEL
}

func (m *MvccObject) GetCf() int32 {
	if m != nil {
		return m.Cf
	}
	return 0
}

func (m *MvccObject) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *MvccObject) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *MvccObject) GetPrimaryKey() []byte {
	if m != nil {
		return m.PrimaryKey
	}
	return nil
}

func (m *MvccObject) GetStartTs() uint64 {
	if m != nil {
		return m.StartTs
	}
	return 0
}

func (m *MvccObject) GetCommitTs() uint64 {
	if m != nil {
		return m.CommitTs
	}
	return 0
}

func (m *MvccObject) GetLatestCommit() uint64 {
	if m != nil {
		return m.LatestCommit
	}
	return 0
}

func (m *MvccObject) GetMvccOp() MvccOp {
	if m != nil {
		return m.MvccOp
	}
	return MvccOp_NULL
}

type Context struct {
	RegionId             uint64   `protobuf:"varint,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Context) Reset()         { *m = Context{} }
func (m *Context) String() string { return proto.CompactTextString(m) }
func (*Context) ProtoMessage()    {}
func (*Context) Descriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{1}
}

func (m *Context) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Context.Unmarshal(m, b)
}
func (m *Context) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Context.Marshal(b, m, deterministic)
}
func (m *Context) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Context.Merge(m, src)
}
func (m *Context) XXX_Size() int {
	return xxx_messageInfo_Context.Size(m)
}
func (m *Context) XXX_DiscardUnknown() {
	xxx_messageInfo_Context.DiscardUnknown(m)
}

var xxx_messageInfo_Context proto.InternalMessageInfo

func (m *Context) GetRegionId() uint64 {
	if m != nil {
		return m.RegionId
	}
	return 0
}

type KeyValue struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyValue) Reset()         { *m = KeyValue{} }
func (m *KeyValue) String() string { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()    {}
func (*KeyValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{2}
}

func (m *KeyValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyValue.Unmarshal(m, b)
}
func (m *KeyValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyValue.Marshal(b, m, deterministic)
}
func (m *KeyValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyValue.Merge(m, src)
}
func (m *KeyValue) XXX_Size() int {
	return xxx_messageInfo_KeyValue.Size(m)
}
func (m *KeyValue) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyValue.DiscardUnknown(m)
}

var xxx_messageInfo_KeyValue proto.InternalMessageInfo

func (m *KeyValue) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *KeyValue) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type PrewriteRequest struct {
	Context              *Context      `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Objects              []*MvccObject `protobuf:"bytes,2,rep,name=objects,proto3" json:"objects,omitempty"`
	PrimaryLock          []byte        `protobuf:"bytes,3,opt,name=primary_lock,json=primaryLock,proto3" json:"primary_lock,omitempty"`
	StartVersion         uint64        `protobuf:"varint,4,opt,name=start_version,json=startVersion,proto3" json:"start_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PrewriteRequest) Reset()         { *m = PrewriteRequest{} }
func (m *PrewriteRequest) String() string { return proto.CompactTextString(m) }
func (*PrewriteRequest) ProtoMessage()    {}
func (*PrewriteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{3}
}

func (m *PrewriteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrewriteRequest.Unmarshal(m, b)
}
func (m *PrewriteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrewriteRequest.Marshal(b, m, deterministic)
}
func (m *PrewriteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrewriteRequest.Merge(m, src)
}
func (m *PrewriteRequest) XXX_Size() int {
	return xxx_messageInfo_PrewriteRequest.Size(m)
}
func (m *PrewriteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrewriteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrewriteRequest proto.InternalMessageInfo

func (m *PrewriteRequest) GetContext() *Context {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *PrewriteRequest) GetObjects() []*MvccObject {
	if m != nil {
		return m.Objects
	}
	return nil
}

func (m *PrewriteRequest) GetPrimaryLock() []byte {
	if m != nil {
		return m.PrimaryLock
	}
	return nil
}

func (m *PrewriteRequest) GetStartVersion() uint64 {
	if m != nil {
		return m.StartVersion
	}
	return 0
}

type PrewriteReponse struct {
	RegionError          Error      `protobuf:"varint,1,opt,name=region_error,json=regionError,proto3,enum=mtikvpb.Error" json:"region_error,omitempty"`
	Errors               []KeyError `protobuf:"varint,2,rep,packed,name=errors,proto3,enum=mtikvpb.KeyError" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PrewriteReponse) Reset()         { *m = PrewriteReponse{} }
func (m *PrewriteReponse) String() string { return proto.CompactTextString(m) }
func (*PrewriteReponse) ProtoMessage()    {}
func (*PrewriteReponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{4}
}

func (m *PrewriteReponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrewriteReponse.Unmarshal(m, b)
}
func (m *PrewriteReponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrewriteReponse.Marshal(b, m, deterministic)
}
func (m *PrewriteReponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrewriteReponse.Merge(m, src)
}
func (m *PrewriteReponse) XXX_Size() int {
	return xxx_messageInfo_PrewriteReponse.Size(m)
}
func (m *PrewriteReponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrewriteReponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrewriteReponse proto.InternalMessageInfo

func (m *PrewriteReponse) GetRegionError() Error {
	if m != nil {
		return m.RegionError
	}
	return Error_RegionNotFound
}

func (m *PrewriteReponse) GetErrors() []KeyError {
	if m != nil {
		return m.Errors
	}
	return nil
}

type CommitRequest struct {
	Context              *Context `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Keys                 [][]byte `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	CommitVersion        uint64   `protobuf:"varint,3,opt,name=commit_version,json=commitVersion,proto3" json:"commit_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommitRequest) Reset()         { *m = CommitRequest{} }
func (m *CommitRequest) String() string { return proto.CompactTextString(m) }
func (*CommitRequest) ProtoMessage()    {}
func (*CommitRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{5}
}

func (m *CommitRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitRequest.Unmarshal(m, b)
}
func (m *CommitRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitRequest.Marshal(b, m, deterministic)
}
func (m *CommitRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitRequest.Merge(m, src)
}
func (m *CommitRequest) XXX_Size() int {
	return xxx_messageInfo_CommitRequest.Size(m)
}
func (m *CommitRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommitRequest proto.InternalMessageInfo

func (m *CommitRequest) GetContext() *Context {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *CommitRequest) GetKeys() [][]byte {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *CommitRequest) GetCommitVersion() uint64 {
	if m != nil {
		return m.CommitVersion
	}
	return 0
}

type CommitReponse struct {
	RegionError          Error      `protobuf:"varint,1,opt,name=region_error,json=regionError,proto3,enum=mtikvpb.Error" json:"region_error,omitempty"`
	Errors               []KeyError `protobuf:"varint,2,rep,packed,name=errors,proto3,enum=mtikvpb.KeyError" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CommitReponse) Reset()         { *m = CommitReponse{} }
func (m *CommitReponse) String() string { return proto.CompactTextString(m) }
func (*CommitReponse) ProtoMessage()    {}
func (*CommitReponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{6}
}

func (m *CommitReponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitReponse.Unmarshal(m, b)
}
func (m *CommitReponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitReponse.Marshal(b, m, deterministic)
}
func (m *CommitReponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitReponse.Merge(m, src)
}
func (m *CommitReponse) XXX_Size() int {
	return xxx_messageInfo_CommitReponse.Size(m)
}
func (m *CommitReponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitReponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommitReponse proto.InternalMessageInfo

func (m *CommitReponse) GetRegionError() Error {
	if m != nil {
		return m.RegionError
	}
	return Error_RegionNotFound
}

func (m *CommitReponse) GetErrors() []KeyError {
	if m != nil {
		return m.Errors
	}
	return nil
}

type GetRequest struct {
	Context              *Context `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Key                  []byte   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Version              uint64   `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{7}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetContext() *Context {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *GetRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *GetRequest) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

type GetReponse struct {
	RegionError          Error    `protobuf:"varint,1,opt,name=region_error,json=regionError,proto3,enum=mtikvpb.Error" json:"region_error,omitempty"`
	Error                KeyError `protobuf:"varint,2,opt,name=error,proto3,enum=mtikvpb.KeyError" json:"error,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	NotFound             bool     `protobuf:"varint,4,opt,name=not_found,json=notFound,proto3" json:"not_found,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReponse) Reset()         { *m = GetReponse{} }
func (m *GetReponse) String() string { return proto.CompactTextString(m) }
func (*GetReponse) ProtoMessage()    {}
func (*GetReponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{8}
}

func (m *GetReponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReponse.Unmarshal(m, b)
}
func (m *GetReponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReponse.Marshal(b, m, deterministic)
}
func (m *GetReponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReponse.Merge(m, src)
}
func (m *GetReponse) XXX_Size() int {
	return xxx_messageInfo_GetReponse.Size(m)
}
func (m *GetReponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetReponse proto.InternalMessageInfo

func (m *GetReponse) GetRegionError() Error {
	if m != nil {
		return m.RegionError
	}
	return Error_RegionNotFound
}

func (m *GetReponse) GetError() KeyError {
	if m != nil {
		return m.Error
	}
	return KeyError_WriteConflict
}

func (m *GetReponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *GetReponse) GetNotFound() bool {
	if m != nil {
		return m.NotFound
	}
	return false
}

type ResolveLockRequest struct {
	StartVersion         uint64   `protobuf:"varint,1,opt,name=start_version,json=startVersion,proto3" json:"start_version,omitempty"`
	CommitVersion        uint64   `protobuf:"varint,2,opt,name=commit_version,json=commitVersion,proto3" json:"commit_version,omitempty"`
	Keys                 [][]byte `protobuf:"bytes,3,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResolveLockRequest) Reset()         { *m = ResolveLockRequest{} }
func (m *ResolveLockRequest) String() string { return proto.CompactTextString(m) }
func (*ResolveLockRequest) ProtoMessage()    {}
func (*ResolveLockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{9}
}

func (m *ResolveLockRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolveLockRequest.Unmarshal(m, b)
}
func (m *ResolveLockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolveLockRequest.Marshal(b, m, deterministic)
}
func (m *ResolveLockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolveLockRequest.Merge(m, src)
}
func (m *ResolveLockRequest) XXX_Size() int {
	return xxx_messageInfo_ResolveLockRequest.Size(m)
}
func (m *ResolveLockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolveLockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResolveLockRequest proto.InternalMessageInfo

func (m *ResolveLockRequest) GetStartVersion() uint64 {
	if m != nil {
		return m.StartVersion
	}
	return 0
}

func (m *ResolveLockRequest) GetCommitVersion() uint64 {
	if m != nil {
		return m.CommitVersion
	}
	return 0
}

func (m *ResolveLockRequest) GetKeys() [][]byte {
	if m != nil {
		return m.Keys
	}
	return nil
}

type ResolveLockResponse struct {
	RegionError          Error    `protobuf:"varint,1,opt,name=region_error,json=regionError,proto3,enum=mtikvpb.Error" json:"region_error,omitempty"`
	Error                KeyError `protobuf:"varint,2,opt,name=error,proto3,enum=mtikvpb.KeyError" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResolveLockResponse) Reset()         { *m = ResolveLockResponse{} }
func (m *ResolveLockResponse) String() string { return proto.CompactTextString(m) }
func (*ResolveLockResponse) ProtoMessage()    {}
func (*ResolveLockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{10}
}

func (m *ResolveLockResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResolveLockResponse.Unmarshal(m, b)
}
func (m *ResolveLockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResolveLockResponse.Marshal(b, m, deterministic)
}
func (m *ResolveLockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolveLockResponse.Merge(m, src)
}
func (m *ResolveLockResponse) XXX_Size() int {
	return xxx_messageInfo_ResolveLockResponse.Size(m)
}
func (m *ResolveLockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolveLockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResolveLockResponse proto.InternalMessageInfo

func (m *ResolveLockResponse) GetRegionError() Error {
	if m != nil {
		return m.RegionError
	}
	return Error_RegionNotFound
}

func (m *ResolveLockResponse) GetError() KeyError {
	if m != nil {
		return m.Error
	}
	return KeyError_WriteConflict
}

type GCRequest struct {
	SafePoint            uint64   `protobuf:"varint,1,opt,name=safe_point,json=safePoint,proto3" json:"safe_point,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GCRequest) Reset()         { *m = GCRequest{} }
func (m *GCRequest) String() string { return proto.CompactTextString(m) }
func (*GCRequest) ProtoMessage()    {}
func (*GCRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{11}
}

func (m *GCRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GCRequest.Unmarshal(m, b)
}
func (m *GCRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GCRequest.Marshal(b, m, deterministic)
}
func (m *GCRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GCRequest.Merge(m, src)
}
func (m *GCRequest) XXX_Size() int {
	return xxx_messageInfo_GCRequest.Size(m)
}
func (m *GCRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GCRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GCRequest proto.InternalMessageInfo

func (m *GCRequest) GetSafePoint() uint64 {
	if m != nil {
		return m.SafePoint
	}
	return 0
}

type GCResponse struct {
	RegionError          Error    `protobuf:"varint,1,opt,name=region_error,json=regionError,proto3,enum=mtikvpb.Error" json:"region_error,omitempty"`
	Error                KeyError `protobuf:"varint,2,opt,name=error,proto3,enum=mtikvpb.KeyError" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GCResponse) Reset()         { *m = GCResponse{} }
func (m *GCResponse) String() string { return proto.CompactTextString(m) }
func (*GCResponse) ProtoMessage()    {}
func (*GCResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{12}
}

func (m *GCResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GCResponse.Unmarshal(m, b)
}
func (m *GCResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GCResponse.Marshal(b, m, deterministic)
}
func (m *GCResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GCResponse.Merge(m, src)
}
func (m *GCResponse) XXX_Size() int {
	return xxx_messageInfo_GCResponse.Size(m)
}
func (m *GCResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GCResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GCResponse proto.InternalMessageInfo

func (m *GCResponse) GetRegionError() Error {
	if m != nil {
		return m.RegionError
	}
	return Error_RegionNotFound
}

func (m *GCResponse) GetError() KeyError {
	if m != nil {
		return m.Error
	}
	return KeyError_WriteConflict
}

type RawGetRequest struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Cf                   string   `protobuf:"bytes,2,opt,name=cf,proto3" json:"cf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawGetRequest) Reset()         { *m = RawGetRequest{} }
func (m *RawGetRequest) String() string { return proto.CompactTextString(m) }
func (*RawGetRequest) ProtoMessage()    {}
func (*RawGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{13}
}

func (m *RawGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawGetRequest.Unmarshal(m, b)
}
func (m *RawGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawGetRequest.Marshal(b, m, deterministic)
}
func (m *RawGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawGetRequest.Merge(m, src)
}
func (m *RawGetRequest) XXX_Size() int {
	return xxx_messageInfo_RawGetRequest.Size(m)
}
func (m *RawGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RawGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RawGetRequest proto.InternalMessageInfo

func (m *RawGetRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *RawGetRequest) GetCf() string {
	if m != nil {
		return m.Cf
	}
	return ""
}

type RawGetResponse struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	NotFound             bool     `protobuf:"varint,2,opt,name=not_found,json=notFound,proto3" json:"not_found,omitempty"`
	RegionError          Error    `protobuf:"varint,3,opt,name=region_error,json=regionError,proto3,enum=mtikvpb.Error" json:"region_error,omitempty"`
	Error                KeyError `protobuf:"varint,4,opt,name=error,proto3,enum=mtikvpb.KeyError" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawGetResponse) Reset()         { *m = RawGetResponse{} }
func (m *RawGetResponse) String() string { return proto.CompactTextString(m) }
func (*RawGetResponse) ProtoMessage()    {}
func (*RawGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{14}
}

func (m *RawGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawGetResponse.Unmarshal(m, b)
}
func (m *RawGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawGetResponse.Marshal(b, m, deterministic)
}
func (m *RawGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawGetResponse.Merge(m, src)
}
func (m *RawGetResponse) XXX_Size() int {
	return xxx_messageInfo_RawGetResponse.Size(m)
}
func (m *RawGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RawGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RawGetResponse proto.InternalMessageInfo

func (m *RawGetResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *RawGetResponse) GetNotFound() bool {
	if m != nil {
		return m.NotFound
	}
	return false
}

func (m *RawGetResponse) GetRegionError() Error {
	if m != nil {
		return m.RegionError
	}
	return Error_RegionNotFound
}

func (m *RawGetResponse) GetError() KeyError {
	if m != nil {
		return m.Error
	}
	return KeyError_WriteConflict
}

type RawPutRequest struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Cf                   string   `protobuf:"bytes,3,opt,name=cf,proto3" json:"cf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawPutRequest) Reset()         { *m = RawPutRequest{} }
func (m *RawPutRequest) String() string { return proto.CompactTextString(m) }
func (*RawPutRequest) ProtoMessage()    {}
func (*RawPutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{15}
}

func (m *RawPutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawPutRequest.Unmarshal(m, b)
}
func (m *RawPutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawPutRequest.Marshal(b, m, deterministic)
}
func (m *RawPutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawPutRequest.Merge(m, src)
}
func (m *RawPutRequest) XXX_Size() int {
	return xxx_messageInfo_RawPutRequest.Size(m)
}
func (m *RawPutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RawPutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RawPutRequest proto.InternalMessageInfo

func (m *RawPutRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *RawPutRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *RawPutRequest) GetCf() string {
	if m != nil {
		return m.Cf
	}
	return ""
}

type RawPutResponse struct {
	RegionError          Error    `protobuf:"varint,1,opt,name=region_error,json=regionError,proto3,enum=mtikvpb.Error" json:"region_error,omitempty"`
	Error                KeyError `protobuf:"varint,2,opt,name=error,proto3,enum=mtikvpb.KeyError" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawPutResponse) Reset()         { *m = RawPutResponse{} }
func (m *RawPutResponse) String() string { return proto.CompactTextString(m) }
func (*RawPutResponse) ProtoMessage()    {}
func (*RawPutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{16}
}

func (m *RawPutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawPutResponse.Unmarshal(m, b)
}
func (m *RawPutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawPutResponse.Marshal(b, m, deterministic)
}
func (m *RawPutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawPutResponse.Merge(m, src)
}
func (m *RawPutResponse) XXX_Size() int {
	return xxx_messageInfo_RawPutResponse.Size(m)
}
func (m *RawPutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RawPutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RawPutResponse proto.InternalMessageInfo

func (m *RawPutResponse) GetRegionError() Error {
	if m != nil {
		return m.RegionError
	}
	return Error_RegionNotFound
}

func (m *RawPutResponse) GetError() KeyError {
	if m != nil {
		return m.Error
	}
	return KeyError_WriteConflict
}

type RawDeleteRequest struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Cf                   string   `protobuf:"bytes,2,opt,name=cf,proto3" json:"cf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawDeleteRequest) Reset()         { *m = RawDeleteRequest{} }
func (m *RawDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*RawDeleteRequest) ProtoMessage()    {}
func (*RawDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{17}
}

func (m *RawDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawDeleteRequest.Unmarshal(m, b)
}
func (m *RawDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawDeleteRequest.Marshal(b, m, deterministic)
}
func (m *RawDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawDeleteRequest.Merge(m, src)
}
func (m *RawDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_RawDeleteRequest.Size(m)
}
func (m *RawDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RawDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RawDeleteRequest proto.InternalMessageInfo

func (m *RawDeleteRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *RawDeleteRequest) GetCf() string {
	if m != nil {
		return m.Cf
	}
	return ""
}

type RawDeleteResponse struct {
	RegionError          Error    `protobuf:"varint,1,opt,name=region_error,json=regionError,proto3,enum=mtikvpb.Error" json:"region_error,omitempty"`
	Error                KeyError `protobuf:"varint,2,opt,name=error,proto3,enum=mtikvpb.KeyError" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawDeleteResponse) Reset()         { *m = RawDeleteResponse{} }
func (m *RawDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*RawDeleteResponse) ProtoMessage()    {}
func (*RawDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_185c3bb479740444, []int{18}
}

func (m *RawDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawDeleteResponse.Unmarshal(m, b)
}
func (m *RawDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawDeleteResponse.Marshal(b, m, deterministic)
}
func (m *RawDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawDeleteResponse.Merge(m, src)
}
func (m *RawDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_RawDeleteResponse.Size(m)
}
func (m *RawDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RawDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RawDeleteResponse proto.InternalMessageInfo

func (m *RawDeleteResponse) GetRegionError() Error {
	if m != nil {
		return m.RegionError
	}
	return Error_RegionNotFound
}

func (m *RawDeleteResponse) GetError() KeyError {
	if m != nil {
		return m.Error
	}
	return KeyError_WriteConflict
}

func init() {
	proto.RegisterEnum("mtikvpb.Op", Op_name, Op_value)
	proto.RegisterEnum("mtikvpb.MvccOp", MvccOp_name, MvccOp_value)
	proto.RegisterEnum("mtikvpb.Error", Error_name, Error_value)
	proto.RegisterEnum("mtikvpb.KeyError", KeyError_name, KeyError_value)
	proto.RegisterType((*MvccObject)(nil), "mtikvpb.MvccObject")
	proto.RegisterType((*Context)(nil), "mtikvpb.Context")
	proto.RegisterType((*KeyValue)(nil), "mtikvpb.KeyValue")
	proto.RegisterType((*PrewriteRequest)(nil), "mtikvpb.PrewriteRequest")
	proto.RegisterType((*PrewriteReponse)(nil), "mtikvpb.PrewriteReponse")
	proto.RegisterType((*CommitRequest)(nil), "mtikvpb.CommitRequest")
	proto.RegisterType((*CommitReponse)(nil), "mtikvpb.CommitReponse")
	proto.RegisterType((*GetRequest)(nil), "mtikvpb.GetRequest")
	proto.RegisterType((*GetReponse)(nil), "mtikvpb.GetReponse")
	proto.RegisterType((*ResolveLockRequest)(nil), "mtikvpb.ResolveLockRequest")
	proto.RegisterType((*ResolveLockResponse)(nil), "mtikvpb.ResolveLockResponse")
	proto.RegisterType((*GCRequest)(nil), "mtikvpb.GCRequest")
	proto.RegisterType((*GCResponse)(nil), "mtikvpb.GCResponse")
	proto.RegisterType((*RawGetRequest)(nil), "mtikvpb.RawGetRequest")
	proto.RegisterType((*RawGetResponse)(nil), "mtikvpb.RawGetResponse")
	proto.RegisterType((*RawPutRequest)(nil), "mtikvpb.RawPutRequest")
	proto.RegisterType((*RawPutResponse)(nil), "mtikvpb.RawPutResponse")
	proto.RegisterType((*RawDeleteRequest)(nil), "mtikvpb.RawDeleteRequest")
	proto.RegisterType((*RawDeleteResponse)(nil), "mtikvpb.RawDeleteResponse")
}

func init() { proto.RegisterFile("mtikvpb.proto", fileDescriptor_185c3bb479740444) }

var fileDescriptor_185c3bb479740444 = []byte{
	// 945 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xdd, 0x72, 0x22, 0x45,
	0x14, 0x66, 0x66, 0x80, 0x99, 0x39, 0xfc, 0x64, 0xd2, 0x6b, 0xe9, 0x2c, 0xd1, 0x92, 0x1d, 0x4b,
	0x45, 0xaa, 0xcc, 0x56, 0xd0, 0x2b, 0xbd, 0xd1, 0x25, 0x91, 0x42, 0x92, 0x40, 0x75, 0xb1, 0xbb,
	0x97, 0x14, 0x19, 0x1a, 0x1d, 0x81, 0xe9, 0xd9, 0x99, 0x86, 0xc8, 0x23, 0xf8, 0x0c, 0x5e, 0xf8,
	0x12, 0xbe, 0x9a, 0xf7, 0x56, 0x77, 0xcf, 0x1f, 0x01, 0x4d, 0x6d, 0xaa, 0x92, 0x2b, 0xba, 0xbf,
	0xf3, 0x9d, 0xe9, 0xf3, 0x9d, 0x73, 0xba, 0x0f, 0x50, 0x5b, 0x31, 0x6f, 0xb1, 0x09, 0x6e, 0x4e,
	0x83, 0x90, 0x32, 0x8a, 0xf4, 0x78, 0xeb, 0xfc, 0xa1, 0x02, 0x5c, 0x6d, 0x5c, 0x77, 0x78, 0xf3,
	0x1b, 0x71, 0x19, 0x3a, 0x01, 0x95, 0x06, 0xb6, 0xd2, 0x54, 0x5a, 0xf5, 0x4e, 0xe5, 0x34, 0xf1,
	0x19, 0x06, 0x58, 0xa5, 0x01, 0xaa, 0x83, 0xea, 0xce, 0x6d, 0xb5, 0xa9, 0xb4, 0x4a, 0x58, 0x75,
	0xe7, 0xc8, 0x02, 0x6d, 0x41, 0xb6, 0xb6, 0xd6, 0x54, 0x5a, 0x55, 0xcc, 0x97, 0xe8, 0x03, 0x28,
	0x6d, 0xa6, 0xcb, 0x35, 0xb1, 0x8b, 0x02, 0x93, 0x1b, 0xf4, 0x29, 0x54, 0x82, 0xd0, 0x5b, 0x4d,
	0xc3, 0xed, 0x84, 0xf3, 0x4b, 0xc2, 0x06, 0x31, 0x34, 0x20, 0x5b, 0xf4, 0x1c, 0x8c, 0x88, 0x4d,
	0x43, 0x36, 0x61, 0x91, 0x5d, 0x6e, 0x2a, 0xad, 0x22, 0xd6, 0xc5, 0x7e, 0x1c, 0xa1, 0x13, 0x30,
	0x5d, 0xba, 0x5a, 0x79, 0xc2, 0xa6, 0x0b, 0x9b, 0x21, 0x81, 0x71, 0x84, 0x3e, 0x83, 0xda, 0x72,
	0xca, 0x48, 0xc4, 0x26, 0x12, 0xb2, 0x0d, 0x41, 0xa8, 0x4a, 0xb0, 0x2b, 0x30, 0xd4, 0x02, 0x7d,
	0xb5, 0x71, 0xdd, 0x09, 0x0d, 0x6c, 0x53, 0xe8, 0x3a, 0x4a, 0x75, 0x09, 0xe1, 0x01, 0x2e, 0xaf,
	0xc4, 0xaf, 0xf3, 0x05, 0xe8, 0x5d, 0xea, 0x33, 0xf2, 0x3b, 0xcf, 0x83, 0x19, 0x92, 0x5f, 0x3c,
	0xea, 0x4f, 0xbc, 0x99, 0x48, 0x47, 0x11, 0x1b, 0x12, 0xe8, 0xcf, 0x9c, 0x0e, 0x18, 0x03, 0xb2,
	0x7d, 0x23, 0xb4, 0xc5, 0x39, 0x50, 0x0e, 0xe4, 0x40, 0xcd, 0xe5, 0xc0, 0xf9, 0x5b, 0x81, 0xa3,
	0x51, 0x48, 0x6e, 0x43, 0x8f, 0x11, 0x4c, 0xde, 0xad, 0x49, 0xc4, 0x50, 0x1b, 0x74, 0x57, 0x9e,
	0x27, 0xfc, 0x2b, 0x1d, 0x2b, 0x8d, 0x2c, 0x8e, 0x03, 0x27, 0x04, 0xf4, 0x35, 0xe8, 0x54, 0x94,
	0x28, 0xb2, 0xd5, 0xa6, 0xd6, 0xaa, 0x74, 0x9e, 0xed, 0xaa, 0x10, 0x36, 0x9c, 0x70, 0xd0, 0x0b,
	0xa8, 0x26, 0x29, 0x5f, 0x52, 0x77, 0x11, 0xd7, 0x28, 0x29, 0xc3, 0x25, 0x75, 0x17, 0x3c, 0x79,
	0x32, 0xe9, 0x1b, 0x12, 0x46, 0x1e, 0xf5, 0x45, 0xcd, 0x8a, 0xb8, 0x2a, 0xc0, 0x37, 0x12, 0x73,
	0x68, 0x3e, 0xea, 0x80, 0xfa, 0x11, 0x41, 0x67, 0x50, 0x8d, 0x53, 0x43, 0xc2, 0x90, 0x86, 0x71,
	0xb3, 0xd4, 0xd3, 0x70, 0x2e, 0x38, 0x8a, 0x2b, 0x92, 0x23, 0x36, 0xe8, 0x2b, 0x28, 0x0b, 0xae,
	0x8c, 0xbd, 0xde, 0x39, 0x4e, 0xc9, 0x03, 0xb2, 0x95, 0xfc, 0x98, 0xe0, 0x6c, 0xa0, 0x26, 0xeb,
	0xf6, 0x90, 0x24, 0x21, 0x28, 0x2e, 0xc8, 0x56, 0x9e, 0x52, 0xc5, 0x62, 0x8d, 0x3e, 0x87, 0x7a,
	0xdc, 0x40, 0x89, 0x4e, 0x4d, 0xe8, 0xac, 0x49, 0x34, 0x11, 0xba, 0xca, 0xce, 0x7d, 0x0a, 0x99,
	0x33, 0x80, 0x1e, 0x79, 0x90, 0xc6, 0xb8, 0xe1, 0xd4, 0xac, 0xe1, 0x6c, 0xd0, 0x77, 0xa5, 0x25,
	0x5b, 0xe7, 0x4f, 0x25, 0x3e, 0xe6, 0xc1, 0x92, 0xbe, 0x84, 0x92, 0xe4, 0xaa, 0x82, 0x7b, 0x40,
	0x91, 0xb4, 0x67, 0x5d, 0xaf, 0xe5, 0x6f, 0xfe, 0x09, 0x98, 0x3e, 0x65, 0x93, 0x39, 0x5d, 0xfb,
	0x33, 0xd1, 0x5f, 0x06, 0x36, 0x7c, 0xca, 0x7e, 0xe2, 0x7b, 0x87, 0x01, 0xc2, 0x24, 0xa2, 0xcb,
	0x0d, 0xe1, 0xfd, 0x98, 0xe4, 0x62, 0xaf, 0x2d, 0x95, 0xfd, 0xb6, 0x3c, 0x50, 0x54, 0xf5, 0x40,
	0x51, 0xd3, 0x7e, 0xd0, 0xb2, 0x7e, 0x70, 0xde, 0xc1, 0xb3, 0x9d, 0x53, 0xa3, 0x47, 0xcf, 0x8d,
	0xd3, 0x06, 0xb3, 0xd7, 0x4d, 0xf4, 0x7d, 0x02, 0x10, 0x4d, 0xe7, 0x64, 0x12, 0x50, 0xcf, 0x67,
	0xb1, 0x38, 0x93, 0x23, 0x23, 0x0e, 0x38, 0xbf, 0x02, 0x70, 0xee, 0x13, 0x44, 0x75, 0x06, 0x35,
	0x3c, 0xbd, 0xcd, 0x75, 0xe1, 0xfe, 0x53, 0x96, 0x3d, 0xf8, 0x26, 0x7f, 0xf0, 0x9d, 0xbf, 0x14,
	0xa8, 0x27, 0x3e, 0x71, 0x84, 0x69, 0xdd, 0x95, 0xff, 0xac, 0xbb, 0xba, 0x5b, 0xf7, 0x3d, 0x51,
	0xda, 0x7b, 0x88, 0x2a, 0xde, 0x23, 0xaa, 0x27, 0x44, 0x8d, 0xd6, 0xff, 0x23, 0xea, 0xe0, 0xfb,
	0x1c, 0x4b, 0xd5, 0x52, 0xa9, 0x4b, 0xa1, 0x54, 0x7c, 0xe8, 0x09, 0x6a, 0xf1, 0x2d, 0x58, 0x78,
	0x7a, 0x7b, 0x4e, 0x96, 0x24, 0x9b, 0x0e, 0xf7, 0x97, 0x83, 0xc2, 0x71, 0xce, 0xeb, 0xf1, 0xc3,
	0x6c, 0xbf, 0x00, 0x75, 0x18, 0x20, 0x1d, 0xb4, 0xf3, 0x8b, 0x4b, 0xab, 0xc0, 0x17, 0xa3, 0xd7,
	0x63, 0x4b, 0x41, 0x26, 0x94, 0xf0, 0xab, 0x1f, 0xbb, 0x03, 0x4b, 0x6d, 0xb7, 0xa1, 0x2c, 0xa7,
	0x2a, 0x32, 0xa0, 0x78, 0xfd, 0xfa, 0x92, 0xf3, 0x00, 0xca, 0x23, 0xfc, 0xb6, 0x3f, 0xbe, 0xb0,
	0x14, 0xbe, 0xee, 0x0e, 0xaf, 0xae, 0xfa, 0x63, 0x4b, 0x6d, 0xbf, 0x84, 0x92, 0x0c, 0x00, 0x41,
	0x1d, 0x8b, 0x78, 0xae, 0xe3, 0x1e, 0xb1, 0x0a, 0x1c, 0x1b, 0x90, 0xed, 0x35, 0x65, 0x7d, 0x5f,
	0xda, 0x2c, 0xa5, 0x7d, 0x2a, 0x06, 0xaf, 0xf4, 0x39, 0x86, 0xda, 0x5b, 0x3e, 0x96, 0xba, 0xd4,
	0x9f, 0x2f, 0x3d, 0x97, 0x59, 0x05, 0x74, 0x04, 0x95, 0x01, 0xd9, 0xf6, 0x23, 0x7e, 0xb1, 0xc9,
	0xcc, 0x52, 0x3a, 0xff, 0x68, 0x50, 0xba, 0x1a, 0x7b, 0x8b, 0x0d, 0xfa, 0x01, 0x8c, 0x64, 0x8e,
	0x21, 0x3b, 0xd5, 0x77, 0x67, 0x20, 0x37, 0x0e, 0x59, 0x44, 0x56, 0x9d, 0x02, 0xfa, 0x0e, 0xca,
	0xf1, 0x1f, 0x8a, 0x0f, 0x73, 0x8f, 0x73, 0x6e, 0x52, 0x35, 0xf6, 0xf1, 0xc4, 0xf7, 0x0c, 0xb4,
	0x1e, 0x61, 0x28, 0x1b, 0xd9, 0xd9, 0xad, 0x6b, 0xdc, 0x01, 0x13, 0x97, 0x9f, 0xa1, 0x92, 0x7b,
	0xa6, 0xd0, 0x49, 0xca, 0xda, 0x7f, 0x32, 0x1b, 0x1f, 0x1f, 0x36, 0x46, 0xc9, 0xb7, 0x5e, 0x82,
	0xda, 0xeb, 0x22, 0x94, 0x1d, 0xd4, 0xbd, 0xe7, 0xf0, 0xef, 0xa1, 0x2c, 0xaf, 0x79, 0x4e, 0xeb,
	0xce, 0x5b, 0xd1, 0xf8, 0x68, 0x0f, 0x8f, 0x76, 0x9d, 0x47, 0xeb, 0x3b, 0xce, 0xd9, 0x9d, 0xdc,
	0x75, 0xce, 0x5d, 0x31, 0xa7, 0x80, 0xce, 0xc1, 0x4c, 0x5b, 0x1a, 0x3d, 0xcf, 0xf3, 0x76, 0x2e,
	0x47, 0xa3, 0x71, 0xc8, 0x94, 0x7c, 0xe5, 0x95, 0x09, 0x25, 0x61, 0x1e, 0x29, 0x37, 0x65, 0xf1,
	0x7f, 0xf7, 0x9b, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xb9, 0x8e, 0xd9, 0x4b, 0x00, 0x0b, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MTikvClient is the client API for MTikv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MTikvClient interface {
	Prewrite(ctx context.Context, in *PrewriteRequest, opts ...grpc.CallOption) (*PrewriteReponse, error)
	Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitReponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReponse, error)
	ResolveLock(ctx context.Context, in *ResolveLockRequest, opts ...grpc.CallOption) (*ResolveLockResponse, error)
	GC(ctx context.Context, in *GCRequest, opts ...grpc.CallOption) (*GetReponse, error)
	RawGet(ctx context.Context, in *RawGetRequest, opts ...grpc.CallOption) (*RawGetResponse, error)
	RawPut(ctx context.Context, in *RawPutRequest, opts ...grpc.CallOption) (*RawPutResponse, error)
	RawDelete(ctx context.Context, in *RawDeleteRequest, opts ...grpc.CallOption) (*RawDeleteResponse, error)
}

type mTikvClient struct {
	cc *grpc.ClientConn
}

func NewMTikvClient(cc *grpc.ClientConn) MTikvClient {
	return &mTikvClient{cc}
}

func (c *mTikvClient) Prewrite(ctx context.Context, in *PrewriteRequest, opts ...grpc.CallOption) (*PrewriteReponse, error) {
	out := new(PrewriteReponse)
	err := c.cc.Invoke(ctx, "/mtikvpb.MTikv/Prewrite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mTikvClient) Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitReponse, error) {
	out := new(CommitReponse)
	err := c.cc.Invoke(ctx, "/mtikvpb.MTikv/Commit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mTikvClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetReponse, error) {
	out := new(GetReponse)
	err := c.cc.Invoke(ctx, "/mtikvpb.MTikv/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mTikvClient) ResolveLock(ctx context.Context, in *ResolveLockRequest, opts ...grpc.CallOption) (*ResolveLockResponse, error) {
	out := new(ResolveLockResponse)
	err := c.cc.Invoke(ctx, "/mtikvpb.MTikv/ResolveLock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mTikvClient) GC(ctx context.Context, in *GCRequest, opts ...grpc.CallOption) (*GetReponse, error) {
	out := new(GetReponse)
	err := c.cc.Invoke(ctx, "/mtikvpb.MTikv/GC", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mTikvClient) RawGet(ctx context.Context, in *RawGetRequest, opts ...grpc.CallOption) (*RawGetResponse, error) {
	out := new(RawGetResponse)
	err := c.cc.Invoke(ctx, "/mtikvpb.MTikv/RawGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mTikvClient) RawPut(ctx context.Context, in *RawPutRequest, opts ...grpc.CallOption) (*RawPutResponse, error) {
	out := new(RawPutResponse)
	err := c.cc.Invoke(ctx, "/mtikvpb.MTikv/RawPut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mTikvClient) RawDelete(ctx context.Context, in *RawDeleteRequest, opts ...grpc.CallOption) (*RawDeleteResponse, error) {
	out := new(RawDeleteResponse)
	err := c.cc.Invoke(ctx, "/mtikvpb.MTikv/RawDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MTikvServer is the server API for MTikv service.
type MTikvServer interface {
	Prewrite(context.Context, *PrewriteRequest) (*PrewriteReponse, error)
	Commit(context.Context, *CommitRequest) (*CommitReponse, error)
	Get(context.Context, *GetRequest) (*GetReponse, error)
	ResolveLock(context.Context, *ResolveLockRequest) (*ResolveLockResponse, error)
	GC(context.Context, *GCRequest) (*GetReponse, error)
	RawGet(context.Context, *RawGetRequest) (*RawGetResponse, error)
	RawPut(context.Context, *RawPutRequest) (*RawPutResponse, error)
	RawDelete(context.Context, *RawDeleteRequest) (*RawDeleteResponse, error)
}

// UnimplementedMTikvServer can be embedded to have forward compatible implementations.
type UnimplementedMTikvServer struct {
}

func (*UnimplementedMTikvServer) Prewrite(ctx context.Context, req *PrewriteRequest) (*PrewriteReponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prewrite not implemented")
}
func (*UnimplementedMTikvServer) Commit(ctx context.Context, req *CommitRequest) (*CommitReponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Commit not implemented")
}
func (*UnimplementedMTikvServer) Get(ctx context.Context, req *GetRequest) (*GetReponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedMTikvServer) ResolveLock(ctx context.Context, req *ResolveLockRequest) (*ResolveLockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveLock not implemented")
}
func (*UnimplementedMTikvServer) GC(ctx context.Context, req *GCRequest) (*GetReponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GC not implemented")
}
func (*UnimplementedMTikvServer) RawGet(ctx context.Context, req *RawGetRequest) (*RawGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RawGet not implemented")
}
func (*UnimplementedMTikvServer) RawPut(ctx context.Context, req *RawPutRequest) (*RawPutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RawPut not implemented")
}
func (*UnimplementedMTikvServer) RawDelete(ctx context.Context, req *RawDeleteRequest) (*RawDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RawDelete not implemented")
}

func RegisterMTikvServer(s *grpc.Server, srv MTikvServer) {
	s.RegisterService(&_MTikv_serviceDesc, srv)
}

func _MTikv_Prewrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrewriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MTikvServer).Prewrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtikvpb.MTikv/Prewrite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MTikvServer).Prewrite(ctx, req.(*PrewriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MTikv_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MTikvServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtikvpb.MTikv/Commit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MTikvServer).Commit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MTikv_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MTikvServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtikvpb.MTikv/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MTikvServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MTikv_ResolveLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveLockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MTikvServer).ResolveLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtikvpb.MTikv/ResolveLock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MTikvServer).ResolveLock(ctx, req.(*ResolveLockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MTikv_GC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MTikvServer).GC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtikvpb.MTikv/GC",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MTikvServer).GC(ctx, req.(*GCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MTikv_RawGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MTikvServer).RawGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtikvpb.MTikv/RawGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MTikvServer).RawGet(ctx, req.(*RawGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MTikv_RawPut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawPutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MTikvServer).RawPut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtikvpb.MTikv/RawPut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MTikvServer).RawPut(ctx, req.(*RawPutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MTikv_RawDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MTikvServer).RawDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mtikvpb.MTikv/RawDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MTikvServer).RawDelete(ctx, req.(*RawDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MTikv_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mtikvpb.MTikv",
	HandlerType: (*MTikvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Prewrite",
			Handler:    _MTikv_Prewrite_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _MTikv_Commit_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _MTikv_Get_Handler,
		},
		{
			MethodName: "ResolveLock",
			Handler:    _MTikv_ResolveLock_Handler,
		},
		{
			MethodName: "GC",
			Handler:    _MTikv_GC_Handler,
		},
		{
			MethodName: "RawGet",
			Handler:    _MTikv_RawGet_Handler,
		},
		{
			MethodName: "RawPut",
			Handler:    _MTikv_RawPut_Handler,
		},
		{
			MethodName: "RawDelete",
			Handler:    _MTikv_RawDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mtikvpb.proto",
}
