// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/kvpb/kvpb.proto

package kvpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RawGetRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawGetRequest) Reset()         { *m = RawGetRequest{} }
func (m *RawGetRequest) String() string { return proto.CompactTextString(m) }
func (*RawGetRequest) ProtoMessage()    {}
func (*RawGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c07f2f3f398f44ad, []int{0}
}

func (m *RawGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawGetRequest.Unmarshal(m, b)
}
func (m *RawGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawGetRequest.Marshal(b, m, deterministic)
}
func (m *RawGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawGetRequest.Merge(m, src)
}
func (m *RawGetRequest) XXX_Size() int {
	return xxx_messageInfo_RawGetRequest.Size(m)
}
func (m *RawGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RawGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RawGetRequest proto.InternalMessageInfo

func (m *RawGetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type RawGetResponse struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawGetResponse) Reset()         { *m = RawGetResponse{} }
func (m *RawGetResponse) String() string { return proto.CompactTextString(m) }
func (*RawGetResponse) ProtoMessage()    {}
func (*RawGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c07f2f3f398f44ad, []int{1}
}

func (m *RawGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawGetResponse.Unmarshal(m, b)
}
func (m *RawGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawGetResponse.Marshal(b, m, deterministic)
}
func (m *RawGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawGetResponse.Merge(m, src)
}
func (m *RawGetResponse) XXX_Size() int {
	return xxx_messageInfo_RawGetResponse.Size(m)
}
func (m *RawGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RawGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RawGetResponse proto.InternalMessageInfo

func (m *RawGetResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *RawGetResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type RawPutRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawPutRequest) Reset()         { *m = RawPutRequest{} }
func (m *RawPutRequest) String() string { return proto.CompactTextString(m) }
func (*RawPutRequest) ProtoMessage()    {}
func (*RawPutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c07f2f3f398f44ad, []int{2}
}

func (m *RawPutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawPutRequest.Unmarshal(m, b)
}
func (m *RawPutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawPutRequest.Marshal(b, m, deterministic)
}
func (m *RawPutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawPutRequest.Merge(m, src)
}
func (m *RawPutRequest) XXX_Size() int {
	return xxx_messageInfo_RawPutRequest.Size(m)
}
func (m *RawPutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RawPutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RawPutRequest proto.InternalMessageInfo

func (m *RawPutRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *RawPutRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type RawPutResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawPutResponse) Reset()         { *m = RawPutResponse{} }
func (m *RawPutResponse) String() string { return proto.CompactTextString(m) }
func (*RawPutResponse) ProtoMessage()    {}
func (*RawPutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c07f2f3f398f44ad, []int{3}
}

func (m *RawPutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawPutResponse.Unmarshal(m, b)
}
func (m *RawPutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawPutResponse.Marshal(b, m, deterministic)
}
func (m *RawPutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawPutResponse.Merge(m, src)
}
func (m *RawPutResponse) XXX_Size() int {
	return xxx_messageInfo_RawPutResponse.Size(m)
}
func (m *RawPutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RawPutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RawPutResponse proto.InternalMessageInfo

func (m *RawPutResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type RawDeleteRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawDeleteRequest) Reset()         { *m = RawDeleteRequest{} }
func (m *RawDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*RawDeleteRequest) ProtoMessage()    {}
func (*RawDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c07f2f3f398f44ad, []int{4}
}

func (m *RawDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawDeleteRequest.Unmarshal(m, b)
}
func (m *RawDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawDeleteRequest.Marshal(b, m, deterministic)
}
func (m *RawDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawDeleteRequest.Merge(m, src)
}
func (m *RawDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_RawDeleteRequest.Size(m)
}
func (m *RawDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RawDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RawDeleteRequest proto.InternalMessageInfo

func (m *RawDeleteRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type RawDeleteResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RawDeleteResponse) Reset()         { *m = RawDeleteResponse{} }
func (m *RawDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*RawDeleteResponse) ProtoMessage()    {}
func (*RawDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c07f2f3f398f44ad, []int{5}
}

func (m *RawDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RawDeleteResponse.Unmarshal(m, b)
}
func (m *RawDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RawDeleteResponse.Marshal(b, m, deterministic)
}
func (m *RawDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RawDeleteResponse.Merge(m, src)
}
func (m *RawDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_RawDeleteResponse.Size(m)
}
func (m *RawDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RawDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RawDeleteResponse proto.InternalMessageInfo

func (m *RawDeleteResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*RawGetRequest)(nil), "kvpb.RawGetRequest")
	proto.RegisterType((*RawGetResponse)(nil), "kvpb.RawGetResponse")
	proto.RegisterType((*RawPutRequest)(nil), "kvpb.RawPutRequest")
	proto.RegisterType((*RawPutResponse)(nil), "kvpb.RawPutResponse")
	proto.RegisterType((*RawDeleteRequest)(nil), "kvpb.RawDeleteRequest")
	proto.RegisterType((*RawDeleteResponse)(nil), "kvpb.RawDeleteResponse")
}

func init() { proto.RegisterFile("api/kvpb/kvpb.proto", fileDescriptor_c07f2f3f398f44ad) }

var fileDescriptor_c07f2f3f398f44ad = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0x2c, 0xc8, 0xd4,
	0xcf, 0x2e, 0x2b, 0x48, 0x02, 0x13, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x2c, 0x20, 0xb6,
	0x94, 0x4c, 0x7a, 0x7e, 0x7e, 0x7a, 0x4e, 0xaa, 0x3e, 0x48, 0x45, 0x62, 0x5e, 0x5e, 0x7e, 0x49,
	0x62, 0x49, 0x66, 0x7e, 0x5e, 0x31, 0x44, 0x8d, 0x92, 0x22, 0x17, 0x6f, 0x50, 0x62, 0xb9, 0x7b,
	0x6a, 0x49, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x90, 0x00, 0x17, 0x73, 0x76, 0x6a, 0xa5,
	0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x88, 0xa9, 0x64, 0xc3, 0xc5, 0x07, 0x53, 0x52, 0x5c,
	0x90, 0x9f, 0x57, 0x9c, 0x2a, 0x24, 0xc2, 0xc5, 0x5a, 0x96, 0x98, 0x53, 0x9a, 0x0a, 0x55, 0x05,
	0xe1, 0x80, 0x44, 0x53, 0x8b, 0x8a, 0xf2, 0x8b, 0x24, 0x98, 0x20, 0xa2, 0x60, 0x8e, 0x92, 0x39,
	0xd8, 0x82, 0x80, 0x52, 0xdc, 0x16, 0x20, 0x8c, 0x63, 0x42, 0x32, 0x4e, 0x49, 0x0d, 0x6c, 0x2d,
	0x58, 0x23, 0xc2, 0x5a, 0x88, 0x05, 0x8c, 0xc8, 0x16, 0xa8, 0x70, 0x09, 0x04, 0x25, 0x96, 0xbb,
	0xa4, 0xe6, 0xa4, 0x96, 0xa4, 0xe2, 0xf6, 0x84, 0x26, 0x97, 0x20, 0x92, 0x2a, 0x7c, 0x06, 0x1a,
	0x35, 0x32, 0x71, 0x71, 0x7a, 0x97, 0x05, 0xa7, 0x16, 0x95, 0x65, 0x26, 0xa7, 0x0a, 0xf9, 0x71,
	0xb1, 0x41, 0x7c, 0x2f, 0x24, 0xac, 0x07, 0x0e, 0x5b, 0x94, 0xe0, 0x92, 0x12, 0x41, 0x15, 0x84,
	0x18, 0xac, 0x24, 0xd9, 0x74, 0xf9, 0xc9, 0x64, 0x26, 0x61, 0x21, 0x41, 0x70, 0xa8, 0x17, 0xa5,
	0x26, 0xe7, 0x17, 0xa5, 0xe8, 0x57, 0x67, 0xa7, 0x56, 0xd6, 0x0a, 0x79, 0x83, 0xcd, 0x0b, 0x28,
	0x45, 0x36, 0x0f, 0x11, 0x3a, 0x48, 0xe6, 0x21, 0xf9, 0x5c, 0x49, 0x0c, 0x6c, 0x9e, 0x80, 0x12,
	0x37, 0x92, 0x79, 0x56, 0x8c, 0x5a, 0x42, 0xe1, 0x5c, 0x9c, 0x70, 0x5f, 0x09, 0x89, 0xc1, 0xb5,
	0xa2, 0x04, 0x86, 0x94, 0x38, 0x86, 0x38, 0xaa, 0x2b, 0xb5, 0x30, 0x5d, 0xe9, 0xc4, 0xc7, 0x05,
	0x4e, 0x3c, 0x4e, 0x60, 0x32, 0x80, 0x31, 0x89, 0x0d, 0x9c, 0x5a, 0x8c, 0x01, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x90, 0x31, 0xa5, 0xc8, 0x68, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// KvServiceClient is the client API for KvService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type KvServiceClient interface {
	RawGet(ctx context.Context, in *RawGetRequest, opts ...grpc.CallOption) (*RawGetResponse, error)
	RawPut(ctx context.Context, in *RawPutRequest, opts ...grpc.CallOption) (*RawPutResponse, error)
	RawDelete(ctx context.Context, in *RawDeleteRequest, opts ...grpc.CallOption) (*RawDeleteResponse, error)
}

type kvServiceClient struct {
	cc *grpc.ClientConn
}

func NewKvServiceClient(cc *grpc.ClientConn) KvServiceClient {
	return &kvServiceClient{cc}
}

func (c *kvServiceClient) RawGet(ctx context.Context, in *RawGetRequest, opts ...grpc.CallOption) (*RawGetResponse, error) {
	out := new(RawGetResponse)
	err := c.cc.Invoke(ctx, "/kvpb.KvService/RawGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvServiceClient) RawPut(ctx context.Context, in *RawPutRequest, opts ...grpc.CallOption) (*RawPutResponse, error) {
	out := new(RawPutResponse)
	err := c.cc.Invoke(ctx, "/kvpb.KvService/RawPut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kvServiceClient) RawDelete(ctx context.Context, in *RawDeleteRequest, opts ...grpc.CallOption) (*RawDeleteResponse, error) {
	out := new(RawDeleteResponse)
	err := c.cc.Invoke(ctx, "/kvpb.KvService/RawDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KvServiceServer is the server API for KvService service.
type KvServiceServer interface {
	RawGet(context.Context, *RawGetRequest) (*RawGetResponse, error)
	RawPut(context.Context, *RawPutRequest) (*RawPutResponse, error)
	RawDelete(context.Context, *RawDeleteRequest) (*RawDeleteResponse, error)
}

// UnimplementedKvServiceServer can be embedded to have forward compatible implementations.
type UnimplementedKvServiceServer struct {
}

func (*UnimplementedKvServiceServer) RawGet(ctx context.Context, req *RawGetRequest) (*RawGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RawGet not implemented")
}
func (*UnimplementedKvServiceServer) RawPut(ctx context.Context, req *RawPutRequest) (*RawPutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RawPut not implemented")
}
func (*UnimplementedKvServiceServer) RawDelete(ctx context.Context, req *RawDeleteRequest) (*RawDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RawDelete not implemented")
}

func RegisterKvServiceServer(s *grpc.Server, srv KvServiceServer) {
	s.RegisterService(&_KvService_serviceDesc, srv)
}

func _KvService_RawGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvServiceServer).RawGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kvpb.KvService/RawGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvServiceServer).RawGet(ctx, req.(*RawGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KvService_RawPut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawPutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvServiceServer).RawPut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kvpb.KvService/RawPut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvServiceServer).RawPut(ctx, req.(*RawPutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KvService_RawDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RawDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KvServiceServer).RawDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kvpb.KvService/RawDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KvServiceServer).RawDelete(ctx, req.(*RawDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _KvService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kvpb.KvService",
	HandlerType: (*KvServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RawGet",
			Handler:    _KvService_RawGet_Handler,
		},
		{
			MethodName: "RawPut",
			Handler:    _KvService_RawPut_Handler,
		},
		{
			MethodName: "RawDelete",
			Handler:    _KvService_RawDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/kvpb/kvpb.proto",
}
